proc setData_IFC {} {
  global attrsum badattr countent ifcall ifcall2x2 ifcall2x3 ifcall2x4 ifcDeprecated ifcdoc2x3 inverses ProfAttr tabcolor type

# all 2x2 entities
set ifcall2x2 [lsort [list Ifc2DCompositeCurve IfcActionRequest IfcActor IfcActorRole IfcActuatorType IfcAddress IfcAirTerminalBoxType IfcAirTerminalType IfcAirToAirHeatRecoveryType IfcAlarmType IfcAngularDimension IfcAnnotation IfcAnnotationCurveOccurrence IfcAnnotationFillArea IfcAnnotationFillAreaOccurrence IfcAnnotationOccurrence IfcAnnotationSurfaceOccurrence IfcAnnotationSymbolOccurrence IfcAnnotationTextOccurrence IfcApplication IfcAppliedValue IfcAppliedValueRelationship IfcApproval IfcApprovalActorRelationship IfcApprovalPropertyRelationship IfcApprovalRelationship IfcArbitraryClosedProfileDef IfcArbitraryOpenProfileDef IfcArbitraryProfileDefWithVoids IfcAsset IfcAsymmetricIShapeProfileDef IfcAxis1Placement IfcAxis2Placement2D IfcAxis2Placement3D IfcBSplineCurve IfcBeam IfcBeamType IfcBezierCurve IfcBoilerType IfcBooleanClippingResult IfcBooleanResult IfcBoundaryCondition IfcBoundaryEdgeCondition IfcBoundaryFaceCondition IfcBoundaryNodeCondition IfcBoundaryNodeConditionWarping IfcBoundedCurve IfcBoundedSurface IfcBoundingBox IfcBoxedHalfSpace IfcBuilding IfcBuildingElement IfcBuildingElementComponent IfcBuildingElementComponentType IfcBuildingElementPart IfcBuildingElementProxy IfcBuildingElementType IfcBuildingStorey IfcCShapeProfileDef IfcCableCarrierFittingType IfcCableCarrierSegmentType IfcCableSegmentType IfcCalendarDate IfcCartesianPoint IfcCartesianTransformationOperator IfcCartesianTransformationOperator2D IfcCartesianTransformationOperator2DnonUniform IfcCartesianTransformationOperator3D IfcCartesianTransformationOperator3DnonUniform IfcChamferEdgeFeature IfcChillerType IfcCircle IfcCircleHollowProfileDef IfcCircleProfileDef IfcClassification IfcClassificationItem IfcClassificationItemRelationship IfcClassificationNotation IfcClassificationNotationFacet IfcClassificationReference IfcClosedShell IfcCoilType IfcColourRgb IfcColourSpecification IfcColumn IfcColumnType IfcComplexProperty IfcCompositeCurve IfcCompositeCurveSegment IfcCompositeProfileDef IfcCompressorType IfcCondenserType IfcCondition IfcConditionCriterion IfcConic IfcConnectedFaceSet IfcConnectionCurveGeometry IfcConnectionGeometry IfcConnectionPointGeometry IfcConnectionPortGeometry IfcConnectionSurfaceGeometry IfcConstraint IfcConstraintAggregationRelationship IfcConstraintClassificationRelationship IfcConstraintRelationship IfcConstructionEquipmentResource IfcConstructionMaterialResource IfcConstructionProductResource IfcConstructionResource IfcContextDependentUnit IfcControl IfcControllerType IfcConversionBasedUnit IfcCooledBeamType IfcCoolingTowerType IfcCoordinatedUniversalTimeOffset IfcCostItem IfcCostSchedule IfcCostValue IfcCovering IfcCoveringType IfcCraneRailAShapeProfileDef IfcCraneRailFShapeProfileDef IfcCrewResource IfcCsgSolid IfcCurrencyRelationship IfcCurtainWall IfcCurve IfcCurveBoundedPlane IfcCurveStyle IfcCurveStyleFont IfcCurveStyleFontAndScaling IfcCurveStyleFontPattern IfcDamperType IfcDateAndTime IfcDefinedSymbol IfcDerivedProfileDef IfcDerivedUnit IfcDerivedUnitElement IfcDiameterDimension IfcDimensionCalloutRelationship IfcDimensionCurve IfcDimensionCurveDirectedCallout IfcDimensionCurveTerminator IfcDimensionalExponents IfcDirection IfcDiscreteAccessory IfcDiscreteAccessoryType IfcDistributionChamberElement IfcDistributionChamberElementType IfcDistributionControlElement IfcDistributionControlElementType IfcDistributionElement IfcDistributionElementType IfcDistributionFlowElement IfcDistributionFlowElementType IfcDistributionPort IfcDocumentElectronicFormat IfcDocumentInformation IfcDocumentInformationRelationship IfcDocumentReference IfcDoor IfcDoorLiningProperties IfcDoorPanelProperties IfcDoorStyle IfcDraughtingCallout IfcDraughtingCalloutRelationship IfcDraughtingPreDefinedColour IfcDraughtingPreDefinedCurveFont IfcDraughtingPreDefinedTextFont IfcDuctFittingType IfcDuctSegmentType IfcDuctSilencerType IfcEdge IfcEdgeCurve IfcEdgeFeature IfcEdgeLoop IfcElectricApplianceType IfcElectricDistributionPoint IfcElectricFlowStorageDeviceType IfcElectricGeneratorType IfcElectricHeaterType IfcElectricMotorType IfcElectricTimeControlType IfcElectricalBaseProperties IfcElectricalCircuit IfcElectricalElement IfcElement IfcElementAssembly IfcElementComponent IfcElementComponentType IfcElementQuantity IfcElementType IfcElementarySurface IfcEllipse IfcEllipseProfileDef IfcEnergyConversionDevice IfcEnergyConversionDeviceType IfcEnergyProperties IfcEnvironmentalImpactValue IfcEquipmentElement IfcEquipmentStandard IfcEvaporativeCoolerType IfcEvaporatorType IfcExtendedMaterialProperties IfcExternalReference IfcExternallyDefinedHatchStyle IfcExternallyDefinedSurfaceStyle IfcExternallyDefinedSymbol IfcExternallyDefinedTextFont IfcExtrudedAreaSolid IfcFace IfcFaceBasedSurfaceModel IfcFaceBound IfcFaceOuterBound IfcFaceSurface IfcFacetedBrep IfcFacetedBrepWithVoids IfcFailureConnectionCondition IfcFanType IfcFastener IfcFastenerType IfcFeatureElement IfcFeatureElementAddition IfcFeatureElementSubtraction IfcFillAreaStyle IfcFillAreaStyleHatching IfcFillAreaStyleTileSymbolWithStyle IfcFillAreaStyleTiles IfcFilterType IfcFireSuppressionTerminalType IfcFlowController IfcFlowControllerType IfcFlowFitting IfcFlowFittingType IfcFlowInstrumentType IfcFlowMeterType IfcFlowMovingDevice IfcFlowMovingDeviceType IfcFlowSegment IfcFlowSegmentType IfcFlowStorageDevice IfcFlowStorageDeviceType IfcFlowTerminal IfcFlowTerminalType IfcFlowTreatmentDevice IfcFlowTreatmentDeviceType IfcFluidFlowProperties IfcFooting IfcFuelProperties IfcFurnishingElement IfcFurnishingElementType IfcFurnitureStandard IfcFurnitureType IfcGasTerminalType IfcGeneralMaterialProperties IfcGeneralProfileProperties IfcGeometricCurveSet IfcGeometricRepresentationContext IfcGeometricRepresentationItem IfcGeometricRepresentationSubContext IfcGeometricSet IfcGrid IfcGridAxis IfcGridPlacement IfcGroup IfcHalfSpaceSolid IfcHeatExchangerType IfcHumidifierType IfcHygroscopicMaterialProperties IfcIShapeProfileDef IfcImageTexture IfcInventory IfcIrregularTimeSeries IfcIrregularTimeSeriesValue IfcJunctionBoxType IfcLShapeProfileDef IfcLaborResource IfcLampType IfcLibraryInformation IfcLibraryReference IfcLightDistributionData IfcLightFixtureType IfcLightIntensityDistribution IfcLightSource IfcLightSourceAmbient IfcLightSourceDirectional IfcLightSourceGoniometric IfcLightSourcePositional IfcLightSourceSpot IfcLine IfcLinearDimension IfcLocalPlacement IfcLocalTime IfcLoop IfcManifoldSolidBrep IfcMappedItem IfcMaterial IfcMaterialClassificationRelationship IfcMaterialLayer IfcMaterialLayerSet IfcMaterialLayerSetUsage IfcMaterialList IfcMaterialProperties IfcMeasureWithUnit IfcMechanicalConcreteMaterialProperties IfcMechanicalFastener IfcMechanicalFastenerType IfcMechanicalMaterialProperties IfcMechanicalSteelMaterialProperties IfcMember IfcMemberType IfcMetric IfcMonetaryUnit IfcMotorConnectionType IfcMove IfcNamedUnit IfcObject IfcObjectPlacement IfcObjective IfcOccupant IfcOffsetCurve2D IfcOffsetCurve3D IfcOneDirectionRepeatFactor IfcOpenShell IfcOpeningElement IfcOpticalMaterialProperties IfcOrderAction IfcOrganization IfcOrganizationRelationship IfcOrientedEdge IfcOutletType IfcOwnerHistory IfcParameterizedProfileDef IfcPath IfcPerformanceHistory IfcPermeableCoveringProperties IfcPermit IfcPerson IfcPersonAndOrganization IfcPhysicalComplexQuantity IfcPhysicalQuantity IfcPhysicalSimpleQuantity IfcPile IfcPipeFittingType IfcPipeSegmentType IfcPixelTexture IfcPlacement IfcPlanarBox IfcPlanarExtent IfcPlane IfcPlate IfcPlateType IfcPoint IfcPointOnCurve IfcPointOnSurface IfcPolyLoop IfcPolygonalBoundedHalfSpace IfcPolyline IfcPort IfcPostalAddress IfcPreDefinedColour IfcPreDefinedCurveFont IfcPreDefinedDimensionSymbol IfcPreDefinedItem IfcPreDefinedPointMarkerSymbol IfcPreDefinedSymbol IfcPreDefinedTerminatorSymbol IfcPreDefinedTextFont IfcPresentationLayerAssignment IfcPresentationLayerAssignmentWithStyle IfcPresentationStyleAssignment IfcProcedure IfcProcess IfcProduct IfcProductDefinitionShape IfcProductRepresentation IfcProductsOfCombustionProperties IfcProfileDef IfcProfileProperties IfcProject IfcProjectOrder IfcProjectOrderRecord IfcProjectionCurve IfcProjectionElement IfcProperty IfcPropertyBoundedValue IfcPropertyConstraintRelationship IfcPropertyDefinition IfcPropertyDependencyRelationship IfcPropertyEnumeratedValue IfcPropertyEnumeration IfcPropertyListValue IfcPropertyReferenceValue IfcPropertySet IfcPropertySetDefinition IfcPropertySingleValue IfcPropertyTableValue IfcProtectiveDeviceType IfcProxy IfcPumpType IfcQuantityArea IfcQuantityCount IfcQuantityLength IfcQuantityTime IfcQuantityVolume IfcQuantityWeight IfcRadiusDimension IfcRailing IfcRailingType IfcRamp IfcRampFlight IfcRampFlightType IfcRationalBezierCurve IfcRectangleHollowProfileDef IfcRectangleProfileDef IfcRectangularTrimmedSurface IfcReferencesValueDocument IfcRegularTimeSeries IfcReinforcementBarProperties IfcReinforcementDefinitionProperties IfcReinforcingBar IfcReinforcingElement IfcReinforcingMesh IfcRelAggregates IfcRelAssigns IfcRelAssignsTasks IfcRelAssignsToActor IfcRelAssignsToControl IfcRelAssignsToGroup IfcRelAssignsToProcess IfcRelAssignsToProduct IfcRelAssignsToProjectOrder IfcRelAssignsToResource IfcRelAssociates IfcRelAssociatesAppliedValue IfcRelAssociatesApproval IfcRelAssociatesClassification IfcRelAssociatesConstraint IfcRelAssociatesDocument IfcRelAssociatesLibrary IfcRelAssociatesMaterial IfcRelAssociatesProfileProperties IfcRelConnects IfcRelConnectsElements IfcRelConnectsPathElements IfcRelConnectsPortToElement IfcRelConnectsPorts IfcRelConnectsStructuralActivity IfcRelConnectsStructuralMember IfcRelConnectsWithRealizingElements IfcRelContainedInSpatialStructure IfcRelCoversBldgElements IfcRelDecomposes IfcRelDefines IfcRelDefinesByProperties IfcRelDefinesByType IfcRelFillsElement IfcRelFlowControlElements IfcRelInteractionRequirements IfcRelNests IfcRelOccupiesSpaces IfcRelOverridesProperties IfcRelProjectsElement IfcRelSchedulesCostItems IfcRelSequence IfcRelServicesBuildings IfcRelSpaceBoundary IfcRelVoidsElement IfcRelationship IfcRelaxation IfcRepresentation IfcRepresentationContext IfcRepresentationItem IfcRepresentationMap IfcResource IfcRevolvedAreaSolid IfcRibPlateProfileProperties IfcRoof IfcRoot IfcRoundedEdgeFeature IfcRoundedRectangleProfileDef IfcSIUnit IfcSanitaryTerminalType IfcScheduleTimeControl IfcSectionProperties IfcSectionReinforcementProperties IfcSectionedSpine IfcSensorType IfcServiceLife IfcServiceLifeFactor IfcShapeAspect IfcShapeRepresentation IfcShellBasedSurfaceModel IfcSimpleProperty IfcSite IfcSlab IfcSlabType IfcSlippageConnectionCondition IfcSolidModel IfcSoundProperties IfcSoundValue IfcSpace IfcSpaceHeaterType IfcSpaceProgram IfcSpaceThermalLoadProperties IfcSpatialStructureElement IfcStackTerminalType IfcStair IfcStairFlight IfcStairFlightType IfcStructuralAction IfcStructuralActivity IfcStructuralAnalysisModel IfcStructuralConnection IfcStructuralConnectionCondition IfcStructuralCurveConnection IfcStructuralCurveMember IfcStructuralCurveMemberVarying IfcStructuralItem IfcStructuralLinearAction IfcStructuralLinearActionVarying IfcStructuralLoad IfcStructuralLoadGroup IfcStructuralLoadLinearForce IfcStructuralLoadPlanarForce IfcStructuralLoadSingleDisplacement IfcStructuralLoadSingleDisplacementDistortion IfcStructuralLoadSingleForce IfcStructuralLoadSingleForceWarping IfcStructuralLoadStatic IfcStructuralLoadTemperature IfcStructuralMember IfcStructuralPlanarAction IfcStructuralPlanarActionVarying IfcStructuralPointAction IfcStructuralPointConnection IfcStructuralPointReaction IfcStructuralProfileProperties IfcStructuralReaction IfcStructuralResultGroup IfcStructuralSteelProfileProperties IfcStructuralSurfaceConnection IfcStructuralSurfaceMember IfcStructuralSurfaceMemberVarying IfcStructuredDimensionCallout IfcStyledItem IfcStyledRepresentation IfcSubContractResource IfcSubedge IfcSurface IfcSurfaceCurveSweptAreaSolid IfcSurfaceOfLinearExtrusion IfcSurfaceOfRevolution IfcSurfaceStyle IfcSurfaceStyleLighting IfcSurfaceStyleRefraction IfcSurfaceStyleRendering IfcSurfaceStyleShading IfcSurfaceStyleWithTextures IfcSurfaceTexture IfcSweptAreaSolid IfcSweptDiskSolid IfcSweptSurface IfcSwitchingDeviceType IfcSymbolStyle IfcSystem IfcSystemFurnitureElementType IfcTShapeProfileDef IfcTable IfcTableRow IfcTankType IfcTask IfcTelecomAddress IfcTendon IfcTendonAnchor IfcTerminatorSymbol IfcTextLiteral IfcTextLiteralWithExtent IfcTextStyle IfcTextStyleWithBoxCharacteristics IfcTextStyleWithMirror IfcTextStyleWithSpacing IfcTextureCoordinate IfcTextureCoordinateGenerator IfcTextureMap IfcTextureVertex IfcThermalMaterialProperties IfcTimeSeries IfcTimeSeriesReferenceRelationship IfcTimeSeriesSchedule IfcTimeSeriesValue IfcTopologicalRepresentationItem IfcTopologyRepresentation IfcTransformerType IfcTransportElement IfcTransportElementType IfcTrapeziumProfileDef IfcTrimmedCurve IfcTubeBundleType IfcTwoDirectionRepeatFactor IfcTypeObject IfcTypeProduct IfcUShapeProfileDef IfcUnitAssignment IfcUnitaryEquipmentType IfcValveType IfcVector IfcVertex IfcVertexBasedTextureMap IfcVertexLoop IfcVertexPoint IfcVibrationIsolatorType IfcVirtualElement IfcVirtualGridIntersection IfcWall IfcWallStandardCase IfcWallType IfcWasteTerminalType IfcWaterProperties IfcWindow IfcWindowLiningProperties IfcWindowPanelProperties IfcWindowStyle IfcWorkControl IfcWorkPlan IfcWorkSchedule IfcZShapeProfileDef IfcZone]]

# all 2x3 entities
set ifcall2x3 [lsort [list Ifc2DCompositeCurve IfcActionRequest IfcActor IfcActorRole IfcActuatorType IfcAddress IfcAirTerminalBoxType IfcAirTerminalType IfcAirToAirHeatRecoveryType IfcAlarmType IfcAngularDimension IfcAnnotation IfcAnnotationCurveOccurrence IfcAnnotationFillArea IfcAnnotationFillAreaOccurrence IfcAnnotationOccurrence IfcAnnotationSurface IfcAnnotationSurfaceOccurrence IfcAnnotationSymbolOccurrence IfcAnnotationTextOccurrence IfcApplication IfcAppliedValue IfcAppliedValueRelationship IfcApproval IfcApprovalActorRelationship IfcApprovalPropertyRelationship IfcApprovalRelationship IfcArbitraryClosedProfileDef IfcArbitraryOpenProfileDef IfcArbitraryProfileDefWithVoids IfcAsset IfcAsymmetricIShapeProfileDef IfcAxis1Placement IfcAxis2Placement2D IfcAxis2Placement3D IfcBSplineCurve IfcBeam IfcBeamType IfcBezierCurve IfcBlobTexture IfcBlock IfcBoilerType IfcBooleanClippingResult IfcBooleanResult IfcBoundaryCondition IfcBoundaryEdgeCondition IfcBoundaryFaceCondition IfcBoundaryNodeCondition IfcBoundaryNodeConditionWarping IfcBoundedCurve IfcBoundedSurface IfcBoundingBox IfcBoxedHalfSpace IfcBuilding IfcBuildingElement IfcBuildingElementComponent IfcBuildingElementPart IfcBuildingElementProxy IfcBuildingElementProxyType IfcBuildingElementType IfcBuildingStorey IfcCShapeProfileDef IfcCableCarrierFittingType IfcCableCarrierSegmentType IfcCableSegmentType IfcCalendarDate IfcCartesianPoint IfcCartesianTransformationOperator IfcCartesianTransformationOperator2D IfcCartesianTransformationOperator2DnonUniform IfcCartesianTransformationOperator3D IfcCartesianTransformationOperator3DnonUniform IfcCenterLineProfileDef IfcChamferEdgeFeature IfcChillerType IfcCircle IfcCircleHollowProfileDef IfcCircleProfileDef IfcClassification IfcClassificationItem IfcClassificationItemRelationship IfcClassificationNotation IfcClassificationNotationFacet IfcClassificationReference IfcClosedShell IfcCoilType IfcColourRgb IfcColourSpecification IfcColumn IfcColumnType IfcComplexProperty IfcCompositeCurve IfcCompositeCurveSegment IfcCompositeProfileDef IfcCompressorType IfcCondenserType IfcCondition IfcConditionCriterion IfcConic IfcConnectedFaceSet IfcConnectionCurveGeometry IfcConnectionGeometry IfcConnectionPointEccentricity IfcConnectionPointGeometry IfcConnectionPortGeometry IfcConnectionSurfaceGeometry IfcConstraint IfcConstraintAggregationRelationship IfcConstraintClassificationRelationship IfcConstraintRelationship IfcConstructionEquipmentResource IfcConstructionMaterialResource IfcConstructionProductResource IfcConstructionResource IfcContextDependentUnit IfcControl IfcControllerType IfcConversionBasedUnit IfcCooledBeamType IfcCoolingTowerType IfcCoordinatedUniversalTimeOffset IfcCostItem IfcCostSchedule IfcCostValue IfcCovering IfcCoveringType IfcCraneRailAShapeProfileDef IfcCraneRailFShapeProfileDef IfcCrewResource IfcCsgPrimitive3D IfcCsgSolid IfcCurrencyRelationship IfcCurtainWall IfcCurtainWallType IfcCurve IfcCurveBoundedPlane IfcCurveStyle IfcCurveStyleFont IfcCurveStyleFontAndScaling IfcCurveStyleFontPattern IfcDamperType IfcDateAndTime IfcDefinedSymbol IfcDerivedProfileDef IfcDerivedUnit IfcDerivedUnitElement IfcDiameterDimension IfcDimensionCalloutRelationship IfcDimensionCurve IfcDimensionCurveDirectedCallout IfcDimensionCurveTerminator IfcDimensionPair IfcDimensionalExponents IfcDirection IfcDiscreteAccessory IfcDiscreteAccessoryType IfcDistributionChamberElement IfcDistributionChamberElementType IfcDistributionControlElement IfcDistributionControlElementType IfcDistributionElement IfcDistributionElementType IfcDistributionFlowElement IfcDistributionFlowElementType IfcDistributionPort IfcDocumentElectronicFormat IfcDocumentInformation IfcDocumentInformationRelationship IfcDocumentReference IfcDoor IfcDoorLiningProperties IfcDoorPanelProperties IfcDoorStyle IfcDraughtingCallout IfcDraughtingCalloutRelationship IfcDraughtingPreDefinedColour IfcDraughtingPreDefinedCurveFont IfcDraughtingPreDefinedTextFont IfcDuctFittingType IfcDuctSegmentType IfcDuctSilencerType IfcEdge IfcEdgeCurve IfcEdgeFeature IfcEdgeLoop IfcElectricApplianceType IfcElectricDistributionPoint IfcElectricFlowStorageDeviceType IfcElectricGeneratorType IfcElectricHeaterType IfcElectricMotorType IfcElectricTimeControlType IfcElectricalBaseProperties IfcElectricalCircuit IfcElectricalElement IfcElement IfcElementAssembly IfcElementComponent IfcElementComponentType IfcElementQuantity IfcElementType IfcElementarySurface IfcEllipse IfcEllipseProfileDef IfcEnergyConversionDevice IfcEnergyConversionDeviceType IfcEnergyProperties IfcEnvironmentalImpactValue IfcEquipmentElement IfcEquipmentStandard IfcEvaporativeCoolerType IfcEvaporatorType IfcExtendedMaterialProperties IfcExternalReference IfcExternallyDefinedHatchStyle IfcExternallyDefinedSurfaceStyle IfcExternallyDefinedSymbol IfcExternallyDefinedTextFont IfcExtrudedAreaSolid IfcFace IfcFaceBasedSurfaceModel IfcFaceBound IfcFaceOuterBound IfcFaceSurface IfcFacetedBrep IfcFacetedBrepWithVoids IfcFailureConnectionCondition IfcFanType IfcFastener IfcFastenerType IfcFeatureElement IfcFeatureElementAddition IfcFeatureElementSubtraction IfcFillAreaStyle IfcFillAreaStyleHatching IfcFillAreaStyleTileSymbolWithStyle IfcFillAreaStyleTiles IfcFilterType IfcFireSuppressionTerminalType IfcFlowController IfcFlowControllerType IfcFlowFitting IfcFlowFittingType IfcFlowInstrumentType IfcFlowMeterType IfcFlowMovingDevice IfcFlowMovingDeviceType IfcFlowSegment IfcFlowSegmentType IfcFlowStorageDevice IfcFlowStorageDeviceType IfcFlowTerminal IfcFlowTerminalType IfcFlowTreatmentDevice IfcFlowTreatmentDeviceType IfcFluidFlowProperties IfcFooting IfcFuelProperties IfcFurnishingElement IfcFurnishingElementType IfcFurnitureStandard IfcFurnitureType IfcGasTerminalType IfcGeneralMaterialProperties IfcGeneralProfileProperties IfcGeometricCurveSet IfcGeometricRepresentationContext IfcGeometricRepresentationItem IfcGeometricRepresentationSubContext IfcGeometricSet IfcGrid IfcGridAxis IfcGridPlacement IfcGroup IfcHalfSpaceSolid IfcHeatExchangerType IfcHumidifierType IfcHygroscopicMaterialProperties IfcIShapeProfileDef IfcImageTexture IfcInventory IfcIrregularTimeSeries IfcIrregularTimeSeriesValue IfcJunctionBoxType IfcLShapeProfileDef IfcLaborResource IfcLampType IfcLibraryInformation IfcLibraryReference IfcLightDistributionData IfcLightFixtureType IfcLightIntensityDistribution IfcLightSource IfcLightSourceAmbient IfcLightSourceDirectional IfcLightSourceGoniometric IfcLightSourcePositional IfcLightSourceSpot IfcLine IfcLinearDimension IfcLocalPlacement IfcLocalTime IfcLoop IfcManifoldSolidBrep IfcMappedItem IfcMaterial IfcMaterialClassificationRelationship IfcMaterialDefinitionRepresentation IfcMaterialLayer IfcMaterialLayerSet IfcMaterialLayerSetUsage IfcMaterialList IfcMaterialProperties IfcMeasureWithUnit IfcMechanicalConcreteMaterialProperties IfcMechanicalFastener IfcMechanicalFastenerType IfcMechanicalMaterialProperties IfcMechanicalSteelMaterialProperties IfcMember IfcMemberType IfcMetric IfcMonetaryUnit IfcMotorConnectionType IfcMove IfcNamedUnit IfcObject IfcObjectDefinition IfcObjectPlacement IfcObjective IfcOccupant IfcOffsetCurve2D IfcOffsetCurve3D IfcOneDirectionRepeatFactor IfcOpenShell IfcOpeningElement IfcOpticalMaterialProperties IfcOrderAction IfcOrganization IfcOrganizationRelationship IfcOrientedEdge IfcOutletType IfcOwnerHistory IfcParameterizedProfileDef IfcPath IfcPerformanceHistory IfcPermeableCoveringProperties IfcPermit IfcPerson IfcPersonAndOrganization IfcPhysicalComplexQuantity IfcPhysicalQuantity IfcPhysicalSimpleQuantity IfcPile IfcPipeFittingType IfcPipeSegmentType IfcPixelTexture IfcPlacement IfcPlanarBox IfcPlanarExtent IfcPlane IfcPlate IfcPlateType IfcPoint IfcPointOnCurve IfcPointOnSurface IfcPolyLoop IfcPolygonalBoundedHalfSpace IfcPolyline IfcPort IfcPostalAddress IfcPreDefinedColour IfcPreDefinedCurveFont IfcPreDefinedDimensionSymbol IfcPreDefinedItem IfcPreDefinedPointMarkerSymbol IfcPreDefinedSymbol IfcPreDefinedTerminatorSymbol IfcPreDefinedTextFont IfcPresentationLayerAssignment IfcPresentationLayerWithStyle IfcPresentationStyle IfcPresentationStyleAssignment IfcProcedure IfcProcess IfcProduct IfcProductDefinitionShape IfcProductRepresentation IfcProductsOfCombustionProperties IfcProfileDef IfcProfileProperties IfcProject IfcProjectOrder IfcProjectOrderRecord IfcProjectionCurve IfcProjectionElement IfcProperty IfcPropertyBoundedValue IfcPropertyConstraintRelationship IfcPropertyDefinition IfcPropertyDependencyRelationship IfcPropertyEnumeratedValue IfcPropertyEnumeration IfcPropertyListValue IfcPropertyReferenceValue IfcPropertySet IfcPropertySetDefinition IfcPropertySingleValue IfcPropertyTableValue IfcProtectiveDeviceType IfcProxy IfcPumpType IfcQuantityArea IfcQuantityCount IfcQuantityLength IfcQuantityTime IfcQuantityVolume IfcQuantityWeight IfcRadiusDimension IfcRailing IfcRailingType IfcRamp IfcRampFlight IfcRampFlightType IfcRationalBezierCurve IfcRectangleHollowProfileDef IfcRectangleProfileDef IfcRectangularPyramid IfcRectangularTrimmedSurface IfcReferencesValueDocument IfcRegularTimeSeries IfcReinforcementBarProperties IfcReinforcementDefinitionProperties IfcReinforcingBar IfcReinforcingElement IfcReinforcingMesh IfcRelAggregates IfcRelAssigns IfcRelAssignsTasks IfcRelAssignsToActor IfcRelAssignsToControl IfcRelAssignsToGroup IfcRelAssignsToProcess IfcRelAssignsToProduct IfcRelAssignsToProjectOrder IfcRelAssignsToResource IfcRelAssociates IfcRelAssociatesAppliedValue IfcRelAssociatesApproval IfcRelAssociatesClassification IfcRelAssociatesConstraint IfcRelAssociatesDocument IfcRelAssociatesLibrary IfcRelAssociatesMaterial IfcRelAssociatesProfileProperties IfcRelConnects IfcRelConnectsElements IfcRelConnectsPathElements IfcRelConnectsPortToElement IfcRelConnectsPorts IfcRelConnectsStructuralActivity IfcRelConnectsStructuralElement IfcRelConnectsStructuralMember IfcRelConnectsWithEccentricity IfcRelConnectsWithRealizingElements IfcRelContainedInSpatialStructure IfcRelCoversBldgElements IfcRelCoversSpaces IfcRelDecomposes IfcRelDefines IfcRelDefinesByProperties IfcRelDefinesByType IfcRelFillsElement IfcRelFlowControlElements IfcRelInteractionRequirements IfcRelNests IfcRelOccupiesSpaces IfcRelOverridesProperties IfcRelProjectsElement IfcRelReferencedInSpatialStructure IfcRelSchedulesCostItems IfcRelSequence IfcRelServicesBuildings IfcRelSpaceBoundary IfcRelVoidsElement IfcRelationship IfcRelaxation IfcRepresentation IfcRepresentationContext IfcRepresentationItem IfcRepresentationMap IfcResource IfcRevolvedAreaSolid IfcRibPlateProfileProperties IfcRightCircularCone IfcRightCircularCylinder IfcRoof IfcRoot IfcRoundedEdgeFeature IfcRoundedRectangleProfileDef IfcSIUnit IfcSanitaryTerminalType IfcScheduleTimeControl IfcSectionProperties IfcSectionReinforcementProperties IfcSectionedSpine IfcSensorType IfcServiceLife IfcServiceLifeFactor IfcShapeAspect IfcShapeModel IfcShapeRepresentation IfcShellBasedSurfaceModel IfcSimpleProperty IfcSite IfcSlab IfcSlabType IfcSlippageConnectionCondition IfcSolidModel IfcSoundProperties IfcSoundValue IfcSpace IfcSpaceHeaterType IfcSpaceProgram IfcSpaceThermalLoadProperties IfcSpaceType IfcSpatialStructureElement IfcSpatialStructureElementType IfcSphere IfcStackTerminalType IfcStair IfcStairFlight IfcStairFlightType IfcStructuralAction IfcStructuralActivity IfcStructuralAnalysisModel IfcStructuralConnection IfcStructuralConnectionCondition IfcStructuralCurveConnection IfcStructuralCurveMember IfcStructuralCurveMemberVarying IfcStructuralItem IfcStructuralLinearAction IfcStructuralLinearActionVarying IfcStructuralLoad IfcStructuralLoadGroup IfcStructuralLoadLinearForce IfcStructuralLoadPlanarForce IfcStructuralLoadSingleDisplacement IfcStructuralLoadSingleDisplacementDistortion IfcStructuralLoadSingleForce IfcStructuralLoadSingleForceWarping IfcStructuralLoadStatic IfcStructuralLoadTemperature IfcStructuralMember IfcStructuralPlanarAction IfcStructuralPlanarActionVarying IfcStructuralPointAction IfcStructuralPointConnection IfcStructuralPointReaction IfcStructuralProfileProperties IfcStructuralReaction IfcStructuralResultGroup IfcStructuralSteelProfileProperties IfcStructuralSurfaceConnection IfcStructuralSurfaceMember IfcStructuralSurfaceMemberVarying IfcStructuredDimensionCallout IfcStyleModel IfcStyledItem IfcStyledRepresentation IfcSubContractResource IfcSubedge IfcSurface IfcSurfaceCurveSweptAreaSolid IfcSurfaceOfLinearExtrusion IfcSurfaceOfRevolution IfcSurfaceStyle IfcSurfaceStyleLighting IfcSurfaceStyleRefraction IfcSurfaceStyleRendering IfcSurfaceStyleShading IfcSurfaceStyleWithTextures IfcSurfaceTexture IfcSweptAreaSolid IfcSweptDiskSolid IfcSweptSurface IfcSwitchingDeviceType IfcSymbolStyle IfcSystem IfcSystemFurnitureElementType IfcTShapeProfileDef IfcTable IfcTableRow IfcTankType IfcTask IfcTelecomAddress IfcTendon IfcTendonAnchor IfcTerminatorSymbol IfcTextLiteral IfcTextLiteralWithExtent IfcTextStyle IfcTextStyleFontModel IfcTextStyleForDefinedFont IfcTextStyleTextModel IfcTextStyleWithBoxCharacteristics IfcTextureCoordinate IfcTextureCoordinateGenerator IfcTextureMap IfcTextureVertex IfcThermalMaterialProperties IfcTimeSeries IfcTimeSeriesReferenceRelationship IfcTimeSeriesSchedule IfcTimeSeriesValue IfcTopologicalRepresentationItem IfcTopologyRepresentation IfcTransformerType IfcTransportElement IfcTransportElementType IfcTrapeziumProfileDef IfcTrimmedCurve IfcTubeBundleType IfcTwoDirectionRepeatFactor IfcTypeObject IfcTypeProduct IfcUShapeProfileDef IfcUnitAssignment IfcUnitaryEquipmentType IfcValveType IfcVector IfcVertex IfcVertexBasedTextureMap IfcVertexLoop IfcVertexPoint IfcVibrationIsolatorType IfcVirtualElement IfcVirtualGridIntersection IfcWall IfcWallStandardCase IfcWallType IfcWasteTerminalType IfcWaterProperties IfcWindow IfcWindowLiningProperties IfcWindowPanelProperties IfcWindowStyle IfcWorkControl IfcWorkPlan IfcWorkSchedule IfcZShapeProfileDef IfcZone]]

# all 2x4 entities
set ifcall2x4 [lsort [list IfcActionRequest IfcActor IfcActorRole IfcActuator IfcActuatorType IfcAddress IfcAdvancedBrep IfcAdvancedBrepWithVoids IfcAdvancedFace IfcAirTerminal IfcAirTerminalBox IfcAirTerminalBoxType IfcAirTerminalType IfcAirToAirHeatRecovery IfcAirToAirHeatRecoveryType IfcAlarm IfcAlarmType IfcAnnotation IfcAnnotationFillArea IfcApplication IfcAppliedValue IfcApproval IfcApprovalRelationship IfcArbitraryClosedProfileDef IfcArbitraryOpenProfileDef IfcArbitraryProfileDefWithVoids IfcAsset IfcAsymmetricIShapeProfileDef IfcAudioVisualAppliance IfcAudioVisualApplianceType IfcAxis1Placement IfcAxis2Placement2D IfcAxis2Placement3D IfcBeam IfcBeamStandardCase IfcBeamType IfcBlobTexture IfcBlock IfcBoiler IfcBoilerType IfcBooleanClippingResult IfcBooleanResult IfcBoundaryCondition IfcBoundaryCurve IfcBoundaryEdgeCondition IfcBoundaryFaceCondition IfcBoundaryNodeCondition IfcBoundaryNodeConditionWarping IfcBoundedCurve IfcBoundedSurface IfcBoundingBox IfcBoxedHalfSpace IfcBSplineCurve IfcBSplineCurveWithKnots IfcBSplineSurface IfcBSplineSurfaceWithKnots IfcBuilding IfcBuildingElement IfcBuildingElementPart IfcBuildingElementPartType IfcBuildingElementProxy IfcBuildingElementProxyType IfcBuildingElementType IfcBuildingStorey IfcBuildingSystem IfcBurner IfcBurnerType IfcCableCarrierFitting IfcCableCarrierFittingType IfcCableCarrierSegment IfcCableCarrierSegmentType IfcCableFitting IfcCableFittingType IfcCableSegment IfcCableSegmentType IfcCartesianPoint IfcCartesianPointList IfcCartesianPointList3D IfcCartesianTransformationOperator IfcCartesianTransformationOperator2D IfcCartesianTransformationOperator2DnonUniform IfcCartesianTransformationOperator3D IfcCartesianTransformationOperator3DnonUniform IfcCenterLineProfileDef IfcChiller IfcChillerType IfcChimney IfcChimneyType IfcCircle IfcCircleHollowProfileDef IfcCircleProfileDef IfcCivilElement IfcCivilElementType IfcClassification IfcClassificationReference IfcClosedShell IfcCoil IfcCoilType IfcColourRgb IfcColourRgbList IfcColourSpecification IfcColumn IfcColumnStandardCase IfcColumnType IfcCommunicationsAppliance IfcCommunicationsApplianceType IfcComplexProperty IfcComplexPropertyTemplate IfcCompositeCurve IfcCompositeCurveOnSurface IfcCompositeCurveSegment IfcCompositeProfileDef IfcCompressor IfcCompressorType IfcCondenser IfcCondenserType IfcConic IfcConnectedFaceSet IfcConnectionCurveGeometry IfcConnectionGeometry IfcConnectionPointEccentricity IfcConnectionPointGeometry IfcConnectionSurfaceGeometry IfcConnectionVolumeGeometry IfcConstraint IfcConstructionEquipmentResource IfcConstructionEquipmentResourceType IfcConstructionMaterialResource IfcConstructionMaterialResourceType IfcConstructionProductResource IfcConstructionProductResourceType IfcConstructionResource IfcConstructionResourceType IfcContext IfcContextDependentUnit IfcControl IfcController IfcControllerType IfcConversionBasedUnit IfcConversionBasedUnitWithOffset IfcCooledBeam IfcCooledBeamType IfcCoolingTower IfcCoolingTowerType IfcCoordinateOperation IfcCoordinateReferenceSystem IfcCostItem IfcCostSchedule IfcCostValue IfcCovering IfcCoveringType IfcCrewResource IfcCrewResourceType IfcCsgPrimitive3D IfcCsgSolid IfcCShapeProfileDef IfcCurrencyRelationship IfcCurtainWall IfcCurtainWallType IfcCurve IfcCurveBoundedPlane IfcCurveBoundedSurface IfcCurveStyle IfcCurveStyleFont IfcCurveStyleFontAndScaling IfcCurveStyleFontPattern IfcCylindricalSurface IfcDamper IfcDamperType IfcDerivedProfileDef IfcDerivedUnit IfcDerivedUnitElement IfcDimensionalExponents IfcDirection IfcDiscreteAccessory IfcDiscreteAccessoryType IfcDistributionChamberElement IfcDistributionChamberElementType IfcDistributionCircuit IfcDistributionControlElement IfcDistributionControlElementType IfcDistributionElement IfcDistributionElementType IfcDistributionFlowElement IfcDistributionFlowElementType IfcDistributionPort IfcDistributionSystem IfcDocumentInformation IfcDocumentInformationRelationship IfcDocumentReference IfcDoor IfcDoorLiningProperties IfcDoorPanelProperties IfcDoorStandardCase IfcDoorStyle IfcDoorType IfcDraughtingPreDefinedColour IfcDraughtingPreDefinedCurveFont IfcDuctFitting IfcDuctFittingType IfcDuctSegment IfcDuctSegmentType IfcDuctSilencer IfcDuctSilencerType IfcEdge IfcEdgeCurve IfcEdgeLoop IfcElectricAppliance IfcElectricApplianceType IfcElectricDistributionBoard IfcElectricDistributionBoardType IfcElectricFlowStorageDevice IfcElectricFlowStorageDeviceType IfcElectricGenerator IfcElectricGeneratorType IfcElectricMotor IfcElectricMotorType IfcElectricTimeControl IfcElectricTimeControlType IfcElement IfcElementarySurface IfcElementAssembly IfcElementAssemblyType IfcElementComponent IfcElementComponentType IfcElementQuantity IfcElementType IfcEllipse IfcEllipseProfileDef IfcEnergyConversionDevice IfcEnergyConversionDeviceType IfcEngine IfcEngineType IfcEvaporativeCooler IfcEvaporativeCoolerType IfcEvaporator IfcEvaporatorType IfcEvent IfcEventTime IfcEventType IfcExtendedProperties IfcExternalInformation IfcExternallyDefinedHatchStyle IfcExternallyDefinedSurfaceStyle IfcExternallyDefinedTextFont IfcExternalReference IfcExternalReferenceRelationship IfcExternalSpatialElement IfcExternalSpatialStructureElement IfcExtrudedAreaSolid IfcExtrudedAreaSolidTapered IfcFace IfcFaceBasedSurfaceModel IfcFaceBound IfcFaceOuterBound IfcFaceSurface IfcFacetedBrep IfcFacetedBrepWithVoids IfcFailureConnectionCondition IfcFan IfcFanType IfcFastener IfcFastenerType IfcFeatureElement IfcFeatureElementAddition IfcFeatureElementSubtraction IfcFillAreaStyle IfcFillAreaStyleHatching IfcFillAreaStyleTiles IfcFilter IfcFilterType IfcFireSuppressionTerminal IfcFireSuppressionTerminalType IfcFixedReferenceSweptAreaSolid IfcFlowController IfcFlowControllerType IfcFlowFitting IfcFlowFittingType IfcFlowInstrument IfcFlowInstrumentType IfcFlowMeter IfcFlowMeterType IfcFlowMovingDevice IfcFlowMovingDeviceType IfcFlowSegment IfcFlowSegmentType IfcFlowStorageDevice IfcFlowStorageDeviceType IfcFlowTerminal IfcFlowTerminalType IfcFlowTreatmentDevice IfcFlowTreatmentDeviceType IfcFooting IfcFootingType IfcFurnishingElement IfcFurnishingElementType IfcFurniture IfcFurnitureType IfcGeographicElement IfcGeographicElementType IfcGeometricCurveSet IfcGeometricRepresentationContext IfcGeometricRepresentationItem IfcGeometricRepresentationSubContext IfcGeometricSet IfcGrid IfcGridAxis IfcGridPlacement IfcGroup IfcHalfSpaceSolid IfcHeatExchanger IfcHeatExchangerType IfcHumidifier IfcHumidifierType IfcImageTexture IfcIndexedColourMap IfcIndexedTextureMap IfcIndexedTriangleTextureMap IfcInterceptor IfcInterceptorType IfcInventory IfcIrregularTimeSeries IfcIrregularTimeSeriesValue IfcIShapeProfileDef IfcJunctionBox IfcJunctionBoxType IfcLaborResource IfcLaborResourceType IfcLagTime IfcLamp IfcLampType IfcLibraryInformation IfcLibraryReference IfcLightDistributionData IfcLightFixture IfcLightFixtureType IfcLightIntensityDistribution IfcLightSource IfcLightSourceAmbient IfcLightSourceDirectional IfcLightSourceGoniometric IfcLightSourcePositional IfcLightSourceSpot IfcLine IfcLocalPlacement IfcLoop IfcLShapeProfileDef IfcManifoldSolidBrep IfcMapConversion IfcMappedItem IfcMaterial IfcMaterialClassificationRelationship IfcMaterialConstituent IfcMaterialConstituentSet IfcMaterialDefinition IfcMaterialDefinitionRepresentation IfcMaterialLayer IfcMaterialLayerSet IfcMaterialLayerSetUsage IfcMaterialLayerWithOffsets IfcMaterialList IfcMaterialProfile IfcMaterialProfileSet IfcMaterialProfileSetUsage IfcMaterialProfileSetUsageTapering IfcMaterialProfileWithOffsets IfcMaterialProperties IfcMaterialRelationship IfcMaterialUsageDefinition IfcMeasureWithUnit IfcMechanicalFastener IfcMechanicalFastenerType IfcMedicalDevice IfcMedicalDeviceType IfcMember IfcMemberStandardCase IfcMemberType IfcMetric IfcMirroredProfileDef IfcMonetaryUnit IfcMotorConnection IfcMotorConnectionType IfcNamedUnit IfcObject IfcObjectDefinition IfcObjective IfcObjectPlacement IfcOccupant IfcOffsetCurve2D IfcOffsetCurve3D IfcOpeningElement IfcOpeningStandardCase IfcOpenShell IfcOrganization IfcOrganizationRelationship IfcOrientedEdge IfcOuterBoundaryCurve IfcOutlet IfcOutletType IfcOwnerHistory IfcParameterizedProfileDef IfcPath IfcPcurve IfcPerformanceHistory IfcPermeableCoveringProperties IfcPermit IfcPerson IfcPersonAndOrganization IfcPhysicalComplexQuantity IfcPhysicalQuantity IfcPhysicalSimpleQuantity IfcPile IfcPileType IfcPipeFitting IfcPipeFittingType IfcPipeSegment IfcPipeSegmentType IfcPixelTexture IfcPlacement IfcPlanarBox IfcPlanarExtent IfcPlane IfcPlate IfcPlateStandardCase IfcPlateType IfcPoint IfcPointOnCurve IfcPointOnSurface IfcPolygonalBoundedHalfSpace IfcPolyline IfcPolyLoop IfcPort IfcPostalAddress IfcPreDefinedColour IfcPreDefinedCurveFont IfcPreDefinedItem IfcPreDefinedProperties IfcPreDefinedPropertySet IfcPreDefinedTextFont IfcPresentationItem IfcPresentationLayerAssignment IfcPresentationLayerWithStyle IfcPresentationStyle IfcPresentationStyleAssignment IfcProcedure IfcProcedureType IfcProcess IfcProduct IfcProductDefinitionShape IfcProductRepresentation IfcProfileDef IfcProfileProperties IfcProject IfcProjectedCRS IfcProjectionElement IfcProjectLibrary IfcProjectOrder IfcProperty IfcPropertyAbstraction IfcPropertyBoundedValue IfcPropertyDefinition IfcPropertyDependencyRelationship IfcPropertyEnumeratedValue IfcPropertyEnumeration IfcPropertyListValue IfcPropertyReferenceValue IfcPropertySet IfcPropertySetDefinition IfcPropertySetTemplate IfcPropertySingleValue IfcPropertyTableValue IfcPropertyTemplate IfcPropertyTemplateDefinition IfcProtectiveDevice IfcProtectiveDeviceTrippingUnit IfcProtectiveDeviceTrippingUnitType IfcProtectiveDeviceType IfcProxy IfcPump IfcPumpType IfcQuantityArea IfcQuantityCount IfcQuantityLength IfcQuantitySet IfcQuantityTime IfcQuantityVolume IfcQuantityWeight IfcRailing IfcRailingType IfcRamp IfcRampFlight IfcRampFlightType IfcRampType IfcRationalBSplineCurveWithKnots IfcRationalBSplineSurfaceWithKnots IfcRectangleHollowProfileDef IfcRectangleProfileDef IfcRectangularPyramid IfcRectangularTrimmedSurface IfcRecurrencePattern IfcReference IfcRegularTimeSeries IfcReinforcementBarProperties IfcReinforcementDefinitionProperties IfcReinforcingBar IfcReinforcingBarType IfcReinforcingElement IfcReinforcingElementType IfcReinforcingMesh IfcReinforcingMeshType IfcRelAggregates IfcRelAssigns IfcRelAssignsToActor IfcRelAssignsToControl IfcRelAssignsToGroup IfcRelAssignsToGroupByFactor IfcRelAssignsToProcess IfcRelAssignsToProduct IfcRelAssignsToResource IfcRelAssociates IfcRelAssociatesApproval IfcRelAssociatesClassification IfcRelAssociatesConstraint IfcRelAssociatesDocument IfcRelAssociatesLibrary IfcRelAssociatesMaterial IfcRelationship IfcRelConnects IfcRelConnectsElements IfcRelConnectsPathElements IfcRelConnectsPorts IfcRelConnectsPortToElement IfcRelConnectsStructuralActivity IfcRelConnectsStructuralMember IfcRelConnectsWithEccentricity IfcRelConnectsWithRealizingElements IfcRelContainedInSpatialStructure IfcRelCoversBldgElements IfcRelCoversSpaces IfcRelDeclares IfcRelDecomposes IfcRelDefines IfcRelDefinesByObject IfcRelDefinesByProperties IfcRelDefinesByTemplate IfcRelDefinesByType IfcRelFillsElement IfcRelFlowControlElements IfcRelInterferesElements IfcRelNests IfcRelProjectsElement IfcRelReferencedInSpatialStructure IfcRelSequence IfcRelServicesBuildings IfcRelSpaceBoundary IfcRelSpaceBoundary1stLevel IfcRelSpaceBoundary2ndLevel IfcRelVoidsElement IfcReparametrisedCompositeCurveSegment IfcRepresentation IfcRepresentationContext IfcRepresentationItem IfcRepresentationMap IfcResource IfcResourceApprovalRelationship IfcResourceConstraintRelationship IfcResourceLevelRelationship IfcResourceTime IfcRevolvedAreaSolid IfcRevolvedAreaSolidTapered IfcRightCircularCone IfcRightCircularCylinder IfcRoof IfcRoofType IfcRoot IfcRoundedRectangleProfileDef IfcSanitaryTerminal IfcSanitaryTerminalType IfcSchedulingTime IfcSectionedSpine IfcSectionProperties IfcSectionReinforcementProperties IfcSensor IfcSensorType IfcShadingDevice IfcShadingDeviceType IfcShapeAspect IfcShapeModel IfcShapeRepresentation IfcShellBasedSurfaceModel IfcSimpleProperty IfcSimplePropertyTemplate IfcSite IfcSIUnit IfcSlab IfcSlabElementedCase IfcSlabStandardCase IfcSlabType IfcSlippageConnectionCondition IfcSolarDevice IfcSolarDeviceType IfcSolidModel IfcSpace IfcSpaceHeater IfcSpaceHeaterType IfcSpaceType IfcSpatialElement IfcSpatialElementType IfcSpatialStructureElement IfcSpatialStructureElementType IfcSpatialZone IfcSpatialZoneType IfcSphere IfcStackTerminal IfcStackTerminalType IfcStair IfcStairFlight IfcStairFlightType IfcStairType IfcStructuralAction IfcStructuralActivity IfcStructuralAnalysisModel IfcStructuralConnection IfcStructuralConnectionCondition IfcStructuralCurveAction IfcStructuralCurveConnection IfcStructuralCurveMember IfcStructuralCurveMemberVarying IfcStructuralCurveReaction IfcStructuralItem IfcStructuralLinearAction IfcStructuralLoad IfcStructuralLoadCase IfcStructuralLoadConfiguration IfcStructuralLoadGroup IfcStructuralLoadLinearForce IfcStructuralLoadOrResult IfcStructuralLoadPlanarForce IfcStructuralLoadSingleDisplacement IfcStructuralLoadSingleDisplacementDistortion IfcStructuralLoadSingleForce IfcStructuralLoadSingleForceWarping IfcStructuralLoadStatic IfcStructuralLoadTemperature IfcStructuralMember IfcStructuralPlanarAction IfcStructuralPointAction IfcStructuralPointConnection IfcStructuralPointReaction IfcStructuralReaction IfcStructuralResultGroup IfcStructuralSurfaceAction IfcStructuralSurfaceConnection IfcStructuralSurfaceMember IfcStructuralSurfaceMemberVarying IfcStructuralSurfaceReaction IfcStyledItem IfcStyledRepresentation IfcStyleModel IfcSubContractResource IfcSubContractResourceType IfcSubedge IfcSurface IfcSurfaceCurveSweptAreaSolid IfcSurfaceFeature IfcSurfaceOfLinearExtrusion IfcSurfaceOfRevolution IfcSurfaceReinforcementArea IfcSurfaceStyle IfcSurfaceStyleLighting IfcSurfaceStyleRefraction IfcSurfaceStyleRendering IfcSurfaceStyleShading IfcSurfaceStyleWithTextures IfcSurfaceTexture IfcSweptAreaSolid IfcSweptDiskSolid IfcSweptDiskSolidPolygonal IfcSweptSurface IfcSwitchingDevice IfcSwitchingDeviceType IfcSystem IfcSystemFurnitureElement IfcSystemFurnitureElementType IfcTable IfcTableColumn IfcTableRow IfcTank IfcTankType IfcTask IfcTaskTime IfcTaskTimeRecurring IfcTaskType IfcTelecomAddress IfcTendon IfcTendonAnchor IfcTendonAnchorType IfcTendonType IfcTessellatedFaceSet IfcTessellatedItem IfcTextLiteral IfcTextLiteralWithExtent IfcTextStyle IfcTextStyleFontModel IfcTextStyleForDefinedFont IfcTextStyleTextModel IfcTextureCoordinate IfcTextureCoordinateGenerator IfcTextureMap IfcTextureVertex IfcTextureVertexList IfcTimePeriod IfcTimeSeries IfcTimeSeriesValue IfcTopologicalRepresentationItem IfcTopologyRepresentation IfcTransformer IfcTransformerType IfcTransportElement IfcTransportElementType IfcTrapeziumProfileDef IfcTriangulatedFaceSet IfcTrimmedCurve IfcTShapeProfileDef IfcTubeBundle IfcTubeBundleType IfcTypeObject IfcTypeProcess IfcTypeProduct IfcTypeResource IfcUnitaryControlElement IfcUnitaryControlElementType IfcUnitaryEquipment IfcUnitaryEquipmentType IfcUnitAssignment IfcUShapeProfileDef IfcValve IfcValveType IfcVector IfcVertex IfcVertexLoop IfcVertexPoint IfcVibrationIsolator IfcVibrationIsolatorType IfcVirtualElement IfcVirtualGridIntersection IfcVoidingFeature IfcWall IfcWallElementedCase IfcWallStandardCase IfcWallType IfcWasteTerminal IfcWasteTerminalType IfcWindow IfcWindowLiningProperties IfcWindowPanelProperties IfcWindowStandardCase IfcWindowStyle IfcWindowType IfcWorkCalendar IfcWorkControl IfcWorkPlan IfcWorkSchedule IfcWorkTime IfcZone IfcZShapeProfileDef]]

# all IFC entities
set ifcall [lsort [union [union $ifcall2x3 $ifcall2x4] $ifcall2x2]]

# deprecated 2x3 entities, entities in 2x3 that are not in 2x4
set ifcDeprecated [lsort [lindex [intersect3 $ifcall2x3 $ifcall2x4] 0]]

# -----------------------------------------------------------------------------------------------------
# HasAssignments  	   :  SET OF IfcRelAssigns FOR RelatedObjects;
# IsDecomposedBy 	   :  SET OF IfcRelDecomposes FOR RelatingObject;
# Decomposes 	           :  SET [0:1] OF IfcRelDecomposes FOR RelatedObjects;
# HasAssociations 	   :  SET OF IfcRelAssociates FOR RelatedObjects;
# IsDefinedBy 	           :  SET OF IfcRelDefines FOR RelatedObjects;
# ReferencedBy             :  SET OF IfcRelAssignsToProduct FOR RelatingProduct;
# HasStructuralMember 	   :  SET OF IfcRelConnectsStructuralElement FOR RelatingElement;
# FillsVoids 	           :  SET [0:1] OF IfcRelFillsElement FOR RelatedBuildingElement;
# ConnectedTo 	           :  SET OF IfcRelConnectsElements FOR RelatingElement;
# HasCoverings 	           :  SET OF IfcRelCoversBldgElements FOR RelatingBuildingElement;
# HasProjections 	   :  SET OF IfcRelProjectsElement FOR RelatingElement;
# ReferencedInStructures   :  SET OF IfcRelReferencedInSpatialStructure FOR RelatedElements;
# HasPorts 	           :  SET OF IfcRelConnectsPortToElement FOR RelatedElement;
# HasOpenings 	           :  SET OF IfcRelVoidsElement FOR RelatingBuildingElement;
# IsConnectionRealization  :  SET OF IfcRelConnectsWithRealizingElements FOR RealizingElements;
# ProvidesBoundaries 	   :  SET OF IfcRelSpaceBoundary FOR RelatedBuildingElement;
# ConnectedFrom 	   :  SET OF IfcRelConnectsElements FOR RelatedElement;
# ContainedInStructure 	   :  SET [0:1] OF IfcRelContainedInSpatialStructure FOR RelatedElements;
# 
#   [list IfcClassificationItem ItemOf Contains] \
#   [list IfcComplexProperty HasProperties PartOfComplex] \
#   [list IfcCompositeCurve Segments UsingCurves] \
#   [list IfcGeometricRepresentationSubContext ParentContext HasSubContexts] \
#   [list IfcGrid UAxes PartOfU] \
#   [list IfcGrid VAxes PartOfV] \
#   [list IfcGrid WAxes PartOfW] \
#   [list IfcLocalPlacement PlacementRelTo ReferencedByPlacements] \
#   [list IfcMappedItem MappingSource MapUsage] \
#   [list IfcOrganization Addresses OfOrganization] \
#   [list IfcPerson Addresses OfPerson] \
#   [list IfcPersonAndOrganization TheOrganization Engages] \
#   [list IfcPersonAndOrganization ThePerson EngagedIn] \
#   [list IfcProduct ObjectPlacement PlacesObject] \
#   [list IfcProduct Representation ShapeOfProducts] \
#   [list IfcRepresentation ContextOfItems RepresentationsInContext] \
#   [list IfcRepresentationMap MappedRepresentation RepresentationMap] \
#   [list IfcShapeAspect PartOfProductDefinitionShape HasShapeAspects] \
#   [list IfcStyledItem Item StyledByItem] \
#   [list IfcVirtualGridIntersection IntersectingAxes HasIntersections] \
#   [list IfcMaterialClassificationRelationship ClassifiedMaterial ClassifiedAs] \
#   [list IfcMaterialDefinitionRepresentation RepresentedMaterial HasRepresentation] \
#   [list IfcMaterialLayerSet MaterialLayers ToMaterialLayerSet] \
#   [list IfcPresentationLayerAssignment AssignedItems LayerAssignments] \
#   [list IfcStructuralAnalysisModel HasResults ResultGroupFor] \
#   [list IfcStructuralAnalysisModel LoadedBy LoadGroupFor] \
#   [list IfcStructuralResultGroup ResultForLoadGroup SourceOfResultGroup] \
#   [list IfcRelDefinesByType RelatedObjects IsTypedBy] \
#   [list IfcRelDefinesByType RelatingObjects Types] \

set inverses {}

lappend inverses [list IfcRelAssignsToControl RelatingControl Controls]
lappend inverses [list IfcRelAssignsToGroup RelatingGroup IsGroupedBy]
lappend inverses [list IfcRelAssignsToProduct RelatingProduct ReferencedBy]

lappend inverses [list IfcRelAssociates RelatedObjects HasAssociations]

lappend inverses [list IfcRelConnectsElements RelatedElement ConnectedFrom]
lappend inverses [list IfcRelConnectsElements RelatingElement ConnectedTo]
lappend inverses [list IfcRelConnectsPorts RelatedPort ConnectedFrom]
lappend inverses [list IfcRelConnectsPorts RelatingPort ConnectedTo]
lappend inverses [list IfcRelConnectsPortToElement RelatingPort ContainedIn]

lappend inverses [list IfcRelConnectsStructuralActivity RelatedStructuralActivity AssignedToStructuralItem]
lappend inverses [list IfcRelConnectsStructuralActivity RelatingElement AssignedStructuralActivity]
lappend inverses [list IfcRelConnectsStructuralElement RelatedStructuralMember ReferencesElement]
lappend inverses [list IfcRelConnectsStructuralElement RelatingElement HasStructuralMember]
lappend inverses [list IfcRelConnectsStructuralMember RelatedStructuralConnection ConnectsStructuralMember]
lappend inverses [list IfcRelConnectsStructuralMember RelatingStructuralMember ConnectedBy]

lappend inverses [list IfcRelContainedInSpatialStructure RelatedElements ContainedInStructure]

lappend inverses [list IfcRelCoversBldgElements RelatedCoverings Covers]
lappend inverses [list IfcRelCoversSpaces RelatedCoverings CoversSpaces]
lappend inverses [list IfcRelCoversSpaces RelatedSpace HasCoverings]

lappend inverses [list IfcRelDeclares RelatedDefinitions HasContext]
lappend inverses [list IfcRelDeclares RelatingContext Declares]

lappend inverses [list IfcRelDecomposes RelatedObjects Decomposes]
lappend inverses [list IfcRelDecomposes RelatingObject IsDecomposedBy]

lappend inverses [list IfcRelDefines RelatedObjects IsDefinedBy]
lappend inverses [list IfcRelDefines RelatingObjects Defines]
lappend inverses [list IfcRelDefinesByObject RelatedObjects IsDeclaredBy]
lappend inverses [list IfcRelDefinesByObject RelatingObjects Declares]
lappend inverses [list IfcRelDefinesByTemplate RelatedPropertySets IsDefinedBy]
lappend inverses [list IfcRelDefinesByTemplate RelatingTemplate Defines]

lappend inverses [list IfcRelDefinesByProperties RelatedObjects IsDefinedBy]
lappend inverses [list IfcRelDefinesByProperties RelatingPropertyDefinition Defines]

lappend inverses [list IfcRelFillsElement RelatedBuildingElement FillsVoids]
lappend inverses [list IfcRelFillsElement RelatingOpeningElement HasFillings]

lappend inverses [list IfcRelFlowControlElements RelatedControlElements AssignedToFlowElement]
lappend inverses [list IfcRelFlowControlElements RelatingFlowElement HasControlElements]

lappend inverses [list IfcRelNests RelatedObjects Nests]
lappend inverses [list IfcRelNests RelatingObjects IsNestedBy]

lappend inverses [list IfcRelServicesBuildings RelatingSystem ServicesBuildings]

lappend inverses [list IfcRelSpaceBoundary RelatingSpace BoundedBy]

lappend inverses [list IfcRelVoidsElement RelatedOpeningElement VoidsElements]
lappend inverses [list IfcRelVoidsElement RelatingBuildingElement HasOpenings]

# -----------------------------------------------------------------------------------------------------
# entity attributes that cause a crash

set badattr(IfcBSplineSurfaceWithKnots) {ControlPointsList}
set badattr(IfcColourRgbList) {ColourList}
set badattr(IfcCartesianPointList) {CoordList}
set badattr(IfcCartesianPointList3D) {CoordList}
set badattr(IfcDirectionList) {DirectionList}
set badattr(IfcIndexedTriangleTextureMap) {TexCoordIndex}
set badattr(IfcRationalBSplineSurfaceWithKnots) {ControlPointsList WeightsData}
set badattr(IfcStructuralLoadConfiguration) {Locations}
set badattr(IfcTextureVertexList) {TexCoordsList}
set badattr(IfcTriangulatedFaceSet) {CoordIndex NormalIndex}

# -----------------------------------------------------------------------------------------------------
# count these attributes for summary

set attrsum {}

# -----------------------------------------------------------------------------------------------------
# count these IFC entities

set countent(IFC) [lsort [list IfcAnnotationSurfaceOccurrence IfcAnnotationTextOccurrence IfcArbitraryClosedProfileDef IfcArbitraryOpenProfileDef IfcArbitraryProfileDefWithVoids IfcAxis2Placement2D IfcAxis2Placement3D IfcBooleanClippingResult IfcBoundaryEdgeCondition IfcBoundaryNodeCondition IfcBoundingBox IfcBoxedHalfSpace IfcCartesianPoint IfcCartesianTransformationOperator2D IfcCartesianTransformationOperator3D IfcCircle IfcClosedShell IfcColourRgb IfcComplexProperty IfcCompositeCurve IfcCompositeCurveSegment IfcConnectedFaceSet IfcConnectionCurveGeometry IfcConnectionSurfaceGeometry IfcCurveBoundedPlane IfcCurveStyle IfcCurveStyleFont IfcCurveStyleFontAndScaling IfcCurveStyleFontPattern IfcDirection IfcDoorLiningProperties IfcDoorPanelProperties IfcDoorStyle IfcDraughtingPreDefinedColour IfcDraughtingPreDefinedCurveFont IfcEdge IfcElementQuantity IfcFace IfcFaceBasedSurfaceModel IfcFaceBound IfcFaceOuterBound IfcFacetedBrep IfcFillAreaStyle IfcFillAreaStyleHatching IfcGeometricCurveSet IfcGeometricSet IfcGeneralProfileProperties IfcHalfSpaceSolid IfcLine IfcLocalPlacement IfcMappedItem IfcMaterial IfcMaterialClassificationRelationship IfcMaterialDefinitionRepresentation IfcMaterialLayer IfcMaterialLayerSet IfcMaterialLayerSetUsage IfcMechanicalSteelMaterialProperties IfcOpenShell IfcPlanarExtent IfcPlane IfcPolyLoop IfcPolygonalBoundedHalfSpace IfcPolyline IfcPresentationLayerAssignment IfcPresentationLayerWithStyle IfcPresentationStyleAssignment IfcProductDefinitionShape IfcProductRepresentation IfcPropertyBoundedValue IfcPropertyEnumeratedValue IfcPropertyEnumeration IfcPropertyListValue IfcPropertySet IfcPropertySingleValue IfcQuantityArea IfcQuantityLength IfcQuantitySet IfcQuantityVolume IfcQuantityWeight IfcRelAssociatesMaterial IfcRelAssociatesProfileProperties IfcRelConnectsPathElements IfcRelConnectsPorts IfcRelConnectsPortToElement IfcRelConnectsStructuralElement IfcRelDefinesByProperties IfcRelFillsElement IfcRelVoidsElement IfcRepresentation IfcRepresentationMap IfcShapeRepresentation IfcShellBasedSurfaceModel IfcStructuralLoadLinearForce IfcStructuralLoadSingleDisplacement IfcStructuralLoadSingleForce IfcStyledItem IfcStyledRepresentation IfcSurfaceStyle IfcSurfaceStyleRendering IfcSurfaceStyleShading IfcTextLiteralWithExtent IfcTextStyle IfcTextStyleFontModel IfcTextStyleForDefinedFont IfcTextStyleTextModel IfcTopologyRepresentation IfcTrimmedCurve IfcVector IfcVertexPoint IfcWindowLiningProperties IfcWindowPanelProperties IfcWindowStyle]]

# -----------------------------------------------------------------------------------------------------
# profile attributes

set ProfAttr(IfcIShapeProfileDef) [list FilletRadius]
set ProfAttr(IfcTShapeProfileDef) [list FilletRadius FlangeEdgeRadius WebEdgeRadius WebSlope FlangeSlope CentreOfGravityInY]
set ProfAttr(IfcLShapeProfileDef) [list FilletRadius EdgeRadius LegSlope CentreOfGravityInX CentreOfGravityInY]
set ProfAttr(IfcUShapeProfileDef) [list FilletRadius EdgeRadius FlangeSlope CentreOfGravityInX]
set ProfAttr(IfcCShapeProfileDef) [list InternalFilletRadius CentreOfGravityInX]
set ProfAttr(IfcZShapeProfileDef) [list FilletRadius EdgeRadius]
set ProfAttr(IfcRectangleHollowShapeProfileDef) [list InnerFilletRadius OuterFilletRadius CentreOfGravityInX]

# -----------------------------------------------------------------------------------------------------

# 2x3 entities by resourse, needed for URL to 2x3 documentation
set ifc2x3(ifcactorresource) [list ifcactorrole ifcactorselect ifcaddress ifcaddresstypeenum ifcorganization ifcorganizationrelationship ifcperson ifcpersonandorganization ifcpostaladdress ifcroleenum ifctelecomaddress]
set ifc2x3(ifcapprovalresource) [list ifcapproval ifcapprovalactorrelationship ifcapprovalpropertyrelationship ifcapprovalrelationship]
set ifc2x3(ifcarchitecturedomain) [list ifcpermeablecoveringoperationenum ifcpermeablecoveringproperties ifcrelinteractionrequirements ifcspaceprogram]
set ifc2x3(ifcbuildingcontrolsdomain) [list ifcactuatortype ifcactuatortypeenum ifcalarmtype ifcalarmtypeenum ifccontrollertype ifccontrollertypeenum ifcflowinstrumenttype ifcflowinstrumenttypeenum ifcsensortype ifcsensortypeenum]
set ifc2x3(ifcconstraintresource) [list ifcbenchmarkenum ifcconstraint ifcconstraintaggregationrelationship ifcconstraintclassificationrelationship ifcconstraintenum ifcconstraintrelationship ifclogicaloperatorenum ifcmetric ifcmetricvalueselect ifcobjective ifcobjectiveenum ifcpropertyconstraintrelationship]
set ifc2x3(ifcconstructionmgmtdomain) [list ifcconstructionequipmentresource ifcconstructionmaterialresource ifcconstructionproductresource ifcconstructionresource ifccrewresource ifclaborresource ifcresourceconsumptionenum ifcsubcontractresource]
set ifc2x3(ifccontrolextension) [list ifcperformancehistory ifcrelassociatesapproval ifcrelassociatesconstraint ifctimeseriesschedule ifctimeseriesscheduletypeenum]
set ifc2x3(ifccostresource) [list ifcappliedvalue ifcappliedvaluerelationship ifcappliedvalueselect ifcarithmeticoperatorenum ifccostvalue ifccurrencyrelationship ifcenvironmentalimpactcategoryenum ifcenvironmentalimpactvalue ifcreferencesvaluedocument]
set ifc2x3(ifcdatetimeresource) [list ifcaheadorbehind ifccalendardate ifccoordinateduniversaltimeoffset ifcdateandtime ifcdatetimeselect ifcdayinmonthnumber ifcdaylightsavinghour ifchourinday ifcleapyear ifclocaltime ifcminuteinhour ifcmonthinyearnumber ifcsecondinminute ifcvalidcalendardate ifcvalidtime ifcyearnumber]
set ifc2x3(ifcelectricaldomain) [list ifccablecarrierfittingtype ifccablecarrierfittingtypeenum ifccablecarriersegmenttype ifccablecarriersegmenttypeenum ifccablesegmenttype ifccablesegmenttypeenum ifcelectricalcircuit ifcelectricappliancetype ifcelectricappliancetypeenum ifcelectricdistributionpoint ifcelectricdistributionpointfunctionenum ifcelectricflowstoragedevicetype ifcelectricflowstoragedevicetypeenum ifcelectricgeneratortype ifcelectricgeneratortypeenum ifcelectricheatertype ifcelectricheatertypeenum ifcelectricmotortype ifcelectricmotortypeenum ifcelectrictimecontroltype ifcelectrictimecontroltypeenum ifcjunctionboxtype ifcjunctionboxtypeenum ifclamptype ifclamptypeenum ifclightfixturetype ifclightfixturetypeenum ifcmotorconnectiontype ifcmotorconnectiontypeenum ifcoutlettype ifcoutlettypeenum ifcprotectivedevicetype ifcprotectivedevicetypeenum ifcswitchingdevicetype ifcswitchingdevicetypeenum ifctransformertype ifctransformertypeenum]
set ifc2x3(ifcexternalreferenceresource) [list ifcclassification ifcclassificationitem ifcclassificationitemrelationship ifcclassificationnotation ifcclassificationnotationfacet ifcclassificationnotationselect ifcclassificationreference ifcdocumentconfidentialityenum ifcdocumentelectronicformat ifcdocumentinformation ifcdocumentinformationrelationship ifcdocumentreference ifcdocumentselect ifcdocumentstatusenum ifcexternalreference ifclibraryinformation ifclibraryreference ifclibraryselect]
set ifc2x3(ifcfacilitiesmgmtdomain) [list ifcactionrequest ifccondition ifcconditioncriterion ifcconditioncriterionselect ifcequipmentstandard ifcfurniturestandard ifcmove ifcorderaction ifcpermit]
set ifc2x3(ifcgeometricconstraintresource) [list ifcconnectioncurvegeometry ifcconnectiongeometry ifcconnectionpointeccentricity ifcconnectionpointgeometry ifcconnectionportgeometry ifcconnectionsurfacegeometry ifccorrectlocalplacement ifccurveoredgecurve ifcgridaxis ifcgridplacement ifclocalplacement ifcobjectplacement ifcpointorvertexpoint ifcsurfaceorfacesurface ifcvirtualgridintersection]
set ifc2x3(ifcgeometricmodelresource) [list ifcblock ifcbooleanclippingresult ifcbooleanoperand ifcbooleanoperator ifcbooleanresult ifcboundingbox ifcboxedhalfspace ifccsgprimitive3d ifccsgselect ifccsgsolid ifcextrudedareasolid ifcfacebasedsurfacemodel ifcfacetedbrep ifcfacetedbrepwithvoids ifcgeometriccurveset ifcgeometricset ifcgeometricsetselect ifchalfspacesolid ifcmanifoldsolidbrep ifcpolygonalboundedhalfspace ifcrectangularpyramid ifcrevolvedareasolid ifcrightcircularcone ifcrightcircularcylinder ifcsectionedspine ifcshellbasedsurfacemodel ifcsolidmodel ifcsphere ifcsurfacecurvesweptareasolid ifcsweptareasolid ifcsweptdisksolid]
set ifc2x3(ifcgeometryresource) [list ifc2dcompositecurve ifcaxis1placement ifcaxis2placement ifcaxis2placement2d ifcaxis2placement3d ifcbaseaxis ifcbeziercurve ifcboundedcurve ifcboundedsurface ifcbsplinecurve ifcbsplinecurveform ifcbuild2axes ifcbuildaxes ifccartesianpoint ifccartesiantransformationoperator ifccartesiantransformationoperator2d ifccartesiantransformationoperator2dnonuniform ifccartesiantransformationoperator3d ifccartesiantransformationoperator3dnonuniform ifccircle ifccompositecurve ifccompositecurvesegment ifcconic ifccrossproduct ifccurve ifccurveboundedplane ifccurvedim ifccurveweightspositive ifcdimensioncount ifcdirection ifcdotproduct ifcelementarysurface ifcellipse ifcfirstprojaxis ifcgeometricrepresentationitem ifcline ifclisttoarray ifcmappeditem ifcnormalise ifcoffsetcurve2d ifcoffsetcurve3d ifcorthogonalcomplement ifcplacement ifcplane ifcpoint ifcpointoncurve ifcpointonsurface ifcpolyline ifcrationalbeziercurve ifcrectangulartrimmedsurface ifcrepresentationitem ifcrepresentationmap ifcsameaxis2placement ifcsamecartesianpoint ifcsamedirection ifcsamevalue ifcscalartimesvector ifcsecondprojaxis ifcsurface ifcsurfaceoflinearextrusion ifcsurfaceofrevolution ifcsweptsurface ifctransitioncode ifctrimmedcurve ifctrimmingpreference ifctrimmingselect ifcvector ifcvectordifference ifcvectorordirection ifcvectorsum]
set ifc2x3(ifchvacdomain) [list ifcairterminalboxtype ifcairterminalboxtypeenum ifcairterminaltype ifcairterminaltypeenum ifcairtoairheatrecoverytype ifcairtoairheatrecoverytypeenum ifcboilertype ifcboilertypeenum ifcchillertype ifcchillertypeenum ifccoiltype ifccoiltypeenum ifccompressortype ifccompressortypeenum ifccondensertype ifccondensertypeenum ifccooledbeamtype ifccooledbeamtypeenum ifccoolingtowertype ifccoolingtowertypeenum ifcdampertype ifcdampertypeenum ifcductfittingtype ifcductfittingtypeenum ifcductsegmenttype ifcductsegmenttypeenum ifcductsilencertype ifcductsilencertypeenum ifcevaporativecoolertype ifcevaporativecoolertypeenum ifcevaporatortype ifcevaporatortypeenum ifcfantype ifcfantypeenum ifcfiltertype ifcfiltertypeenum ifcflowmetertype ifcflowmetertypeenum ifcgasterminaltype ifcgasterminaltypeenum ifcheatexchangertype ifcheatexchangertypeenum ifchumidifiertype ifchumidifiertypeenum ifcpipefittingtype ifcpipefittingtypeenum ifcpipesegmenttype ifcpipesegmenttypeenum ifcpumptype ifcpumptypeenum ifcspaceheatertype ifcspaceheatertypeenum ifctanktype ifctanktypeenum ifctubebundletype ifctubebundletypeenum ifcunitaryequipmenttype ifcunitaryequipmenttypeenum ifcvalvetype ifcvalvetypeenum ifcvibrationisolatortype ifcvibrationisolatortypeenum]
set ifc2x3(ifckernel) [list ifcactor ifccontrol ifccorrectobjectassignment ifcgroup ifcobject ifcobjectdefinition ifcobjecttypeenum ifcprocess ifcproduct ifcproject ifcpropertydefinition ifcpropertyset ifcpropertysetdefinition ifcproxy ifcrelaggregates ifcrelassigns ifcrelassignstoactor ifcrelassignstocontrol ifcrelassignstogroup ifcrelassignstoprocess ifcrelassignstoproduct ifcrelassignstoresource ifcrelassociates ifcrelassociatesclassification ifcrelassociatesdocument ifcrelassociateslibrary ifcrelationship ifcrelconnects ifcreldecomposes ifcreldefines ifcreldefinesbyproperties ifcreldefinesbytype ifcrelnests ifcreloverridesproperties ifcrelsequence ifcresource ifcroot ifcsequenceenum ifcsingleprojectinstance ifctypeobject ifctypeproduct]
set ifc2x3(ifcmaterialpropertyresource) [list ifcextendedmaterialproperties ifcfuelproperties ifcgeneralmaterialproperties ifchygroscopicmaterialproperties ifcmaterialproperties ifcmechanicalconcretematerialproperties ifcmechanicalmaterialproperties ifcmechanicalsteelmaterialproperties ifcopticalmaterialproperties ifcproductsofcombustionproperties ifcrelaxation ifcthermalmaterialproperties ifcwaterproperties]
set ifc2x3(ifcmaterialresource) [list ifcdirectionsenseenum ifclayersetdirectionenum ifcmaterial ifcmaterialclassificationrelationship ifcmateriallayer ifcmateriallayerset ifcmateriallayersetusage ifcmateriallist ifcmaterialselect ifcmlstotalthickness]
set ifc2x3(ifcmeasureresource) [list ifcabsorbeddosemeasure ifcaccelerationmeasure ifcamountofsubstancemeasure ifcangularvelocitymeasure ifcareameasure ifcboolean ifccomplexnumber ifccompoundplaneanglemeasure ifccontextdependentmeasure ifccontextdependentunit ifcconversionbasedunit ifccorrectdimensions ifccorrectunitassignment ifccountmeasure ifccurrencyenum ifccurvaturemeasure ifcderivedimensionalexponents ifcderivedmeasurevalue ifcderivedunit ifcderivedunitelement ifcderivedunitenum ifcdescriptivemeasure ifcdimensionalexponents ifcdimensionsforsiunit ifcdoseequivalentmeasure ifcdynamicviscositymeasure ifcelectriccapacitancemeasure ifcelectricchargemeasure ifcelectricconductancemeasure ifcelectriccurrentmeasure ifcelectricresistancemeasure ifcelectricvoltagemeasure ifcenergymeasure ifcforcemeasure ifcfrequencymeasure ifcheatfluxdensitymeasure ifcheatingvaluemeasure ifcidentifier ifcilluminancemeasure ifcinductancemeasure ifcinteger ifcintegercountratemeasure ifcionconcentrationmeasure ifcisothermalmoisturecapacitymeasure ifckinematicviscositymeasure ifclabel ifclengthmeasure ifclinearforcemeasure ifclinearmomentmeasure ifclinearstiffnessmeasure ifclinearvelocitymeasure ifclogical ifcluminousfluxmeasure ifcluminousintensitydistributionmeasure ifcluminousintensitymeasure ifcmagneticfluxdensitymeasure ifcmagneticfluxmeasure ifcmassdensitymeasure ifcmassflowratemeasure ifcmassmeasure ifcmassperlengthmeasure ifcmeasurevalue ifcmeasurewithunit ifcmodulusofelasticitymeasure ifcmodulusoflinearsubgradereactionmeasure ifcmodulusofrotationalsubgradereactionmeasure ifcmodulusofsubgradereactionmeasure ifcmoisturediffusivitymeasure ifcmolecularweightmeasure ifcmomentofinertiameasure ifcmonetarymeasure ifcmonetaryunit ifcnamedunit ifcnormalisedratiomeasure ifcnumericmeasure ifcparametervalue ifcphmeasure ifcplanarforcemeasure ifcplaneanglemeasure ifcpositivelengthmeasure ifcpositiveplaneanglemeasure ifcpositiveratiomeasure ifcpowermeasure ifcpressuremeasure ifcradioactivitymeasure ifcratiomeasure ifcreal ifcrotationalfrequencymeasure ifcrotationalmassmeasure ifcrotationalstiffnessmeasure ifcsectionalareaintegralmeasure ifcsectionmodulusmeasure ifcshearmodulusmeasure ifcsimplevalue ifcsiprefix ifcsiunit ifcsiunitname ifcsolidanglemeasure ifcsoundpowermeasure ifcsoundpressuremeasure ifcspecificheatcapacitymeasure ifctemperaturegradientmeasure ifctext ifcthermaladmittancemeasure ifcthermalconductivitymeasure ifcthermalexpansioncoefficientmeasure ifcthermalresistancemeasure ifcthermaltransmittancemeasure ifcthermodynamictemperaturemeasure ifctimemeasure ifctimestamp ifctorquemeasure ifcunit ifcunitassignment ifcunitenum ifcvalue ifcvaporpermeabilitymeasure ifcvolumemeasure ifcvolumetricflowratemeasure ifcwarpingconstantmeasure ifcwarpingmomentmeasure]
set ifc2x3(ifcplumbingfireprotectiondomain) [list ifcfiresuppressionterminaltype ifcfiresuppressionterminaltypeenum ifcsanitaryterminaltype ifcsanitaryterminaltypeenum ifcstackterminaltype ifcstackterminaltypeenum ifcwasteterminaltype ifcwasteterminaltypeenum]
set ifc2x3(ifcpresentationappearanceresource) [list ifcblobtexture ifccharacterstyleselect ifccolourorfactor ifccorrectfillareastyle ifccurvefontorscaledcurvefontselect ifccurvestyle ifccurvestylefont ifccurvestylefontandscaling ifccurvestylefontpattern ifccurvestylefontselect ifcdraughtingpredefinedcurvefont ifcexternallydefinedhatchstyle ifcexternallydefinedsurfacestyle ifcfillareastyle ifcfillareastylehatching ifcfillareastyletiles ifcfillareastyletileshapeselect ifcfillareastyletilesymbolwithstyle ifcfillstyleselect ifchatchlinedistanceselect ifcimagetexture ifcnullstyle ifconedirectionrepeatfactor ifcpixeltexture ifcpredefinedcurvefont ifcpresentationstyle ifcpresentationstyleassignment ifcpresentationstyleselect ifcreflectancemethodenum ifcsizeselect ifcspecularexponent ifcspecularhighlightselect ifcspecularroughness ifcstyleditem ifcsurfaceside ifcsurfacestyle ifcsurfacestyleelementselect ifcsurfacestylelighting ifcsurfacestylerefraction ifcsurfacestylerendering ifcsurfacestyleshading ifcsurfacestylewithtextures ifcsurfacetexture ifcsurfacetextureenum ifcsymbolstyle ifcsymbolstyleselect ifctextalignment ifctextdecoration ifctextstyle ifctextstylefordefinedfont ifctextstyleselect ifctextstyletextmodel ifctextstylewithboxcharacteristics ifctexttransformation ifctwodirectionrepeatfactor]
set ifc2x3(ifcpresentationdefinitionresource) [list ifcannotationcurveoccurrence ifcannotationfillarea ifcannotationfillareaoccurrence ifcannotationoccurrence ifcannotationsurface ifcannotationsurfaceoccurrence ifcannotationsymboloccurrence ifcannotationtextoccurrence ifcboxalignment ifcdefinedsymbol ifcdefinedsymbolselect ifcexternallydefinedsymbol ifcpredefinedsymbol ifctextliteral ifctextliteralwithextent ifctextpath ifctexturecoordinate ifctexturecoordinategenerator ifctexturemap ifctexturevertex ifcvertexbasedtexturemap]
set ifc2x3(ifcpresentationdimensioningresource) [list ifcangulardimension ifcdiameterdimension ifcdimensioncalloutrelationship ifcdimensioncurve ifcdimensioncurvedirectedcallout ifcdimensioncurveterminator ifcdimensionextentusage ifcdimensionpair ifcdraughtingcallout ifcdraughtingcalloutelement ifcdraughtingcalloutrelationship ifclineardimension ifcpredefineddimensionsymbol ifcpredefinedpointmarkersymbol ifcpredefinedterminatorsymbol ifcprojectioncurve ifcradiusdimension ifcstructureddimensioncallout ifcterminatorsymbol]
set ifc2x3(ifcpresentationorganizationresource) [list ifclayereditem ifclightdistributioncurveenum ifclightdistributiondata ifclightdistributiondatasourceselect ifclightemissionsourceenum ifclightintensitydistribution ifclightsource ifclightsourceambient ifclightsourcedirectional ifclightsourcegoniometric ifclightsourcepositional ifclightsourcespot ifcpresentationlayerassignment ifcpresentationlayerwithstyle]
set ifc2x3(ifcpresentationresource) [list ifccolour ifccolourrgb ifccolourspecification ifcdraughtingpredefinedcolour ifcdraughtingpredefinedtextfont ifcexternallydefinedtextfont ifcfontstyle ifcfontvariant ifcfontweight ifcplanarbox ifcplanarextent ifcpredefinedcolour ifcpredefineditem ifcpredefinedtextfont ifcpresentabletext ifctextfontname ifctextfontselect ifctextstylefontmodel]
set ifc2x3(ifcprocessextension) [list ifcprocedure ifcproceduretypeenum ifcrelassignstasks ifcscheduletimecontrol ifctask ifcworkcontrol ifcworkcontroltypeenum ifcworkplan ifcworkschedule]
set ifc2x3(ifcproductextension) [list ifcannotation ifcassemblyplaceenum ifcbuilding ifcbuildingelement ifcbuildingelementproxy ifcbuildingelementproxytype ifcbuildingelementproxytypeenum ifcbuildingelementtype ifcbuildingstorey ifccovering ifccoveringtype ifccoveringtypeenum ifcdistributionelement ifcdistributionelementtype ifcelectricalelement ifcelement ifcelementassembly ifcelementassemblytypeenum ifcelementcompositionenum ifcelementquantity ifcelementtype ifcequipmentelement ifcfeatureelement ifcfeatureelementaddition ifcfeatureelementsubtraction ifcfurnishingelement ifcfurnishingelementtype ifcgrid ifcinternalorexternalenum ifcopeningelement ifcphysicalorvirtualenum ifcport ifcprojectionelement ifcrelassociatesmaterial ifcrelconnectselements ifcrelconnectsports ifcrelconnectsporttoelement ifcrelconnectswithrealizingelements ifcrelcontainedinspatialstructure ifcrelcoversbldgelements ifcrelcoversspaces ifcrelfillselement ifcrelprojectselement ifcrelreferencedinspatialstructure ifcrelservicesbuildings ifcrelspaceboundary ifcrelvoidselement ifcsite ifcspace ifcspacetype ifcspacetypeenum ifcspatialstructureelement ifcspatialstructureelementtype ifcsystem ifctransportelement ifctransportelementtype ifctransportelementtypeenum ifcvirtualelement ifczone]
set ifc2x3(ifcprofilepropertyresource) [list ifcgeneralprofileproperties ifcprofileproperties ifcreinforcementbarproperties ifcreinforcingbarroleenum ifcreinforcingbarsurfaceenum ifcribplatedirectionenum ifcribplateprofileproperties ifcsectionproperties ifcsectionreinforcementproperties ifcsectiontypeenum ifcstructuralprofileproperties ifcstructuralsteelprofileproperties]
set ifc2x3(ifcprofileresource) [list ifcarbitraryclosedprofiledef ifcarbitraryopenprofiledef ifcarbitraryprofiledefwithvoids ifcasymmetricishapeprofiledef ifccenterlineprofiledef ifccirclehollowprofiledef ifccircleprofiledef ifccompositeprofiledef ifccranerailashapeprofiledef ifccranerailfshapeprofiledef ifccshapeprofiledef ifcderivedprofiledef ifcellipseprofiledef ifcishapeprofiledef ifclshapeprofiledef ifcparameterizedprofiledef ifcprofiledef ifcprofiletypeenum ifcrectanglehollowprofiledef ifcrectangleprofiledef ifcroundedrectangleprofiledef ifctrapeziumprofiledef ifctshapeprofiledef ifcushapeprofiledef ifczshapeprofiledef]
set ifc2x3(ifcpropertyresource) [list ifccomplexproperty ifcobjectreferenceselect ifcproperty ifcpropertyboundedvalue ifcpropertydependencyrelationship ifcpropertyenumeratedvalue ifcpropertyenumeration ifcpropertylistvalue ifcpropertyreferencevalue ifcpropertysinglevalue ifcpropertytablevalue ifcsimpleproperty ifcuniquepropertyname]
set ifc2x3(ifcquantityresource) [list ifcphysicalcomplexquantity ifcphysicalquantity ifcphysicalsimplequantity ifcquantityarea ifcquantitycount ifcquantitylength ifcquantitytime ifcquantityvolume ifcquantityweight]
set ifc2x3(ifcrepresentationresource) [list ifcgeometricprojectionenum ifcgeometricrepresentationcontext ifcgeometricrepresentationsubcontext ifcglobalorlocalenum ifcmaterialdefinitionrepresentation ifcproductdefinitionshape ifcproductrepresentation ifcrepresentation ifcrepresentationcontext ifcrepresentationcontextsamewcs ifcsamevalidprecision ifcshapeaspect ifcshapemodel ifcshaperepresentation ifcshaperepresentationtypes ifcstyledrepresentation ifcstylemodel ifctopologyrepresentation ifctopologyrepresentationtypes]
set ifc2x3(ifcsharedbldgelements) [list ifcbeam ifcbeamtype ifcbeamtypeenum ifccolumn ifccolumntype ifccolumntypeenum ifcconnectiontypeenum ifccurtainwall ifccurtainwalltype ifccurtainwalltypeenum ifcdoor ifcdoorliningproperties ifcdoorpaneloperationenum ifcdoorpanelpositionenum ifcdoorpanelproperties ifcdoorstyle ifcdoorstyleconstructionenum ifcdoorstyleoperationenum ifcmember ifcmembertype ifcmembertypeenum ifcplate ifcplatetype ifcplatetypeenum ifcrailing ifcrailingtype ifcrailingtypeenum ifcramp ifcrampflight ifcrampflighttype ifcrampflighttypeenum ifcramptypeenum ifcrelconnectspathelements ifcroof ifcrooftypeenum ifcslab ifcslabtype ifcslabtypeenum ifcstair ifcstairflight ifcstairflighttype ifcstairflighttypeenum ifcstairtypeenum ifcwall ifcwallstandardcase ifcwalltype ifcwalltypeenum ifcwindow ifcwindowliningproperties ifcwindowpaneloperationenum ifcwindowpanelpositionenum ifcwindowpanelproperties ifcwindowstyle ifcwindowstyleconstructionenum ifcwindowstyleoperationenum]
set ifc2x3(ifcsharedbldgserviceelements) [list ifcdistributionchamberelement ifcdistributionchamberelementtype ifcdistributionchamberelementtypeenum ifcdistributioncontrolelement ifcdistributioncontrolelementtype ifcdistributionflowelement ifcdistributionflowelementtype ifcdistributionport ifcelectricalbaseproperties ifcelectriccurrentenum ifcenergyconversiondevice ifcenergyconversiondevicetype ifcenergyproperties ifcenergysequenceenum ifcflowcontroller ifcflowcontrollertype ifcflowdirectionenum ifcflowfitting ifcflowfittingtype ifcflowmovingdevice ifcflowmovingdevicetype ifcflowsegment ifcflowsegmenttype ifcflowstoragedevice ifcflowstoragedevicetype ifcflowterminal ifcflowterminaltype ifcflowtreatmentdevice ifcflowtreatmentdevicetype ifcfluidflowproperties ifcpropertysourceenum ifcrelflowcontrolelements ifcsoundproperties ifcsoundscaleenum ifcsoundvalue ifcspacethermalloadproperties ifcthermalloadsourceenum ifcthermalloadtypeenum]
set ifc2x3(ifcsharedcomponentelements) [list ifcchamferedgefeature ifcdiscreteaccessory ifcdiscreteaccessorytype ifcedgefeature ifcelementcomponent ifcelementcomponenttype ifcfastener ifcfastenertype ifcmechanicalfastener ifcmechanicalfastenertype ifcroundededgefeature]
set ifc2x3(ifcsharedfacilitieselements) [list ifcasset ifcfurnituretype ifcinventory ifcinventorytypeenum ifcoccupant ifcoccupanttypeenum ifcreloccupiesspaces ifcservicelife ifcservicelifefactor ifcservicelifefactortypeenum ifcservicelifetypeenum ifcsystemfurnitureelementtype]
set ifc2x3(ifcsharedmgmtelements) [list ifccostitem ifccostschedule ifccostscheduletypeenum ifcprojectorder ifcprojectorderrecord ifcprojectorderrecordtypeenum ifcprojectordertypeenum ifcrelassignstoprojectorder ifcrelassociatesappliedvalue ifcrelschedulescostitems]
set ifc2x3(ifcstructuralanalysisdomain) [list ifcactionsourcetypeenum ifcactiontypeenum ifcaddtobeginoflist ifcanalysismodeltypeenum ifcanalysistheorytypeenum ifcloadgrouptypeenum ifcorientationselect ifcprojectedortruelengthenum ifcrelassociatesprofileproperties ifcrelconnectsstructuralactivity ifcrelconnectsstructuralelement ifcrelconnectsstructuralmember ifcrelconnectswitheccentricity ifcstructuralaction ifcstructuralactivity ifcstructuralactivityassignmentselect ifcstructuralanalysismodel ifcstructuralconnection ifcstructuralcurveconnection ifcstructuralcurvemember ifcstructuralcurvemembervarying ifcstructuralcurvetypeenum ifcstructuralitem ifcstructurallinearaction ifcstructurallinearactionvarying ifcstructuralloadgroup ifcstructuralmember ifcstructuralplanaraction ifcstructuralplanaractionvarying ifcstructuralpointaction ifcstructuralpointconnection ifcstructuralpointreaction ifcstructuralreaction ifcstructuralresultgroup ifcstructuralsurfaceconnection ifcstructuralsurfacemember ifcstructuralsurfacemembervarying ifcstructuralsurfacetypeenum]
set ifc2x3(ifcstructuralelementsdomain) [list ifcbuildingelementcomponent ifcbuildingelementpart ifcfooting ifcfootingtypeenum ifcpile ifcpileconstructionenum ifcpiletypeenum ifcreinforcementdefinitionproperties ifcreinforcingbar ifcreinforcingelement ifcreinforcingmesh ifctendon ifctendonanchor ifctendontypeenum]
set ifc2x3(ifcstructuralloadresource) [list ifcboundarycondition ifcboundaryedgecondition ifcboundaryfacecondition ifcboundarynodecondition ifcboundarynodeconditionwarping ifcfailureconnectioncondition ifcslippageconnectioncondition ifcstructuralconnectioncondition ifcstructuralload ifcstructuralloadlinearforce ifcstructuralloadplanarforce ifcstructuralloadsingledisplacement ifcstructuralloadsingledisplacementdistortion ifcstructuralloadsingleforce ifcstructuralloadsingleforcewarping ifcstructuralloadstatic ifcstructuralloadtemperature]
set ifc2x3(ifctimeseriesresource) [list ifcdataoriginenum ifcirregulartimeseries ifcirregulartimeseriesvalue ifcregulartimeseries ifctimeseries ifctimeseriesdatatypeenum ifctimeseriesreferencerelationship ifctimeseriesvalue]
set ifc2x3(ifctopologyresource) [list ifcbooleanchoose ifcclosedshell ifcconnectedfaceset ifcedge ifcedgecurve ifcedgeloop ifcface ifcfacebound ifcfaceouterbound ifcfacesurface ifcloop ifcloopheadtotail ifcopenshell ifcorientededge ifcpath ifcpathheadtotail ifcpolyloop ifcshell ifcsubedge ifctopologicalrepresentationitem ifcvertex ifcvertexloop ifcvertexpoint]
set ifc2x3(ifcutilityresource) [list ifcapplication ifcchangeactionenum ifcgloballyuniqueid ifcownerhistory ifcstateenum ifctable ifctablerow]

# set ifcdoc2x3, entities that have documentation based on the above
foreach idx [array names ifc2x3] {foreach item $ifc2x3($idx) {set ifcdoc2x3($item) $idx}}

# -----------------------------------------------------------------------------------------------------
# colors, also set colors in setColorIndex

set tabcolor(PR_BEAM) -1			
set tabcolor(PR_HVAC) 22			
set tabcolor(PR_ELEC) 24			
set tabcolor(PR_SRVC) 27			
set tabcolor(PR_ANAL) 34			
set tabcolor(PR_PROF) 35			
set tabcolor(PR_REPR) 38			
set tabcolor(PR_PRES) 40
set tabcolor(PR_COMM) 42			
set tabcolor(PR_GEOM) 43

# -----------------------------------------------------------------------------------------------------
# representation

set type(PR_REPR) [lsort [list \
  IfcClassification \
  IfcClassificationItem \
  IfcClassificationNotation \
  IfcClassificationNotationFacet \
  IfcClassificationReference \
  IfcCoordinateOperation \
  IfcCoordinateReferenceSystem \
  IfcDocumentElectronicFormat \
  IfcDocumentInformation \
  IfcDocumentReference \
  IfcExternalInformation \
  IfcExternalReference \
  IfcGeometricRepresentationContext \
  IfcGeometricRepresentationItem \
  IfcGeometricRepresentationSubContext \
  IfcLibraryInformation \
  IfcLibraryReference \
  IfcMapConversion \
  IfcMappedItem \
  IfcMaterialDefinitionRepresentation \
  IfcProductDefinitionShape \
  IfcProductRepresentation \
  IfcProjectedCRS \
  IfcRepresentation \
  IfcRepresentationContext \
  IfcRepresentationItem \
  IfcRepresentationMap \
  IfcShapeAspect \
  IfcShapeModel \
  IfcShapeRepresentation \
  IfcStyleModel \
  IfcStyledRepresentation \
  IfcTopologicalRepresentationItem \
  IfcTopologyRepresentation]]

# -----------------------------------------------------------------------------------------------------
# shape profile
set type(PR_PROF) [lsort [list \
  IfcArbitraryClosedProfileDef \
  IfcArbitraryOpenProfileDef \
  IfcArbitraryProfileDefWithVoids \
  IfcAsymmetricIShapeProfileDef \
  IfcCShapeProfileDef \
  IfcCenterLineProfileDef \
  IfcCircleHollowProfileDef \
  IfcCircleProfileDef \
  IfcCompositeProfileDef \
  IfcCraneRailAShapeProfileDef \
  IfcCraneRailFShapeProfileDef \
  IfcDerivedProfileDef \
  IfcEllipseProfileDef \
  IfcExtrudedAreaSolid \
  IfcExtrudedAreaSolidTapered \
  IfcGeneralProfileProperties \
  IfcIShapeProfileDef \
  IfcLShapeProfileDef \
  IfcMirroredProfileDef \
  IfcParameterizedProfileDef \
  IfcProfileDef \
  IfcRectangleHollowProfileDef \
  IfcRectangleProfileDef \
  IfcRevolvedAreaSolid \
  IfcRevolvedAreaSolidTapered \
  IfcRoundedRectangleProfileDef \
  IfcSurfaceCurveSweptAreaSolid \
  IfcSweptAreaSolid \
  IfcSweptDiskSolid \
  IfcSweptDiskSolidPolygonal \
  IfcSweptSurface \
  IfcTShapeProfileDef \
  IfcTrapeziumProfileDef \
  IfcUShapeProfileDef \
  IfcZShapeProfileDef]]	        

# -----------------------------------------------------------------------------------------------------
# building elements
set type(PR_BEAM) [lsort [list \
  IfcBeam \
  IfcBeamStandardCase \
  IfcBeamType \
  IfcBuildingElement \
  IfcBuildingElementComponent \
  IfcBuildingElementComponentType \
  IfcBuildingElementPart \
  IfcBuildingElementPartType \
  IfcBuildingElementProxy \
  IfcBuildingElementProxyType \
  IfcBuildingElementType \
  IfcBuildingSystem \
  IfcChimney \
  IfcChimneyType \
  IfcColumn \
  IfcColumnStandardCase \
  IfcColumnType \
  IfcCovering \
  IfcCoveringType \
  IfcCurtainWall \
  IfcCurtainWallType \
  IfcDiscreteAccessory \
  IfcDiscreteAccessoryType \
  IfcDoor \
  IfcDoorStandardCase \
  IfcDoorType \
  IfcElement \
  IfcElementType \
  IfcElementAssembly \
  IfcElementAssemblyType \
  IfcElementComponent \
  IfcElementComponentType \
  IfcEquipmentElement \
  IfcExternalSpatialElement \
  IfcExternalSpatialStructureElement \
  IfcFastener \
  IfcFastenerType \
  IfcFeatureElement \
  IfcFeatureElementAddition \
  IfcFeatureElementSubtraction \
  IfcFooting \
  IfcFootingType \
  IfcFurnishingElement \
  IfcFurnishingElementType \
  IfcFurniture \
  IfcFurnitureStandard \
  IfcFurnitureType \
  IfcGeographicElement \
  IfcGeographicElementType \
  IfcInventory \
  IfcMechanicalFastener \
  IfcMechanicalFastenerType \
  IfcMember \
  IfcMemberStandardCase \
  IfcMemberType \
  IfcOccupant \
  IfcOpeningElement \
  IfcOpeningStandardCase \
  IfcPile \
  IfcPileType \
  IfcPlate \
  IfcPlateStandardCase \
  IfcPlateType \
  IfcPort \
  IfcProjectionElement \
  IfcRailing \
  IfcRailingType \
  IfcRamp \
  IfcRampFlight \
  IfcRampFlightType \
  IfcRampType \
  IfcReinforcingBar \
  IfcReinforcingBarType \
  IfcReinforcingElement \
  IfcReinforcingElementType \
  IfcReinforcingMesh \
  IfcReinforcingMeshType \
  IfcRoof \
  IfcRoofType \
  IfcShadingDevice \
  IfcShadingDeviceType \
  IfcSlab \
  IfcSlabElementedCase \
  IfcSlabStandardCase \
  IfcSlabType \
  IfcSpace \
  IfcSpaceProgram \
  IfcSpaceType \
  IfcSpatialElement \
  IfcSpatialElementType \
  IfcSpatialStructureElement \
  IfcSpatialStructureElementType \
  IfcSpatialZone \
  IfcSpatialZoneType \
  IfcStair \
  IfcStairFlight \
  IfcStairFlightType \
  IfcStairType \
  IfcSurfaceFeature \
  IfcSystemFurnitureElement \
  IfcSystemFurnitureElementType \
  IfcTendon \
  IfcTendonAnchor \
  IfcTendonAnchorType \
  IfcTendonType \
  IfcTransportElement \
  IfcTransportElementType \
  IfcTypeObject \
  IfcVirtualElement \
  IfcVoidingFeature \
  IfcWall \
  IfcWallElementedCase \
  IfcWallStandardCase \
  IfcWallType \
  IfcWindow \
  IfcWindowStandardCase \
  IfcWindowType \
  IfcZone]]
			
# -----------------------------------------------------------------------------------------------------
# common
set type(PR_COMM) [lsort [list \
  IfcActionRequest \
  IfcActor \
  IfcActorRole \
  IfcAddress \
  IfcApplication \
  IfcAppliedValue \
  IfcApproval \
  IfcAsset \
  IfcBuilding \
  IfcBuildingStorey \
  IfcCalendarDate \
  IfcCivilElement \
  IfcCivilElementType \
  IfcCondition \
  IfcConditionCriterion \
  IfcConstraint \
  IfcConstructionEquipmentResource \
  IfcConstructionEquipmentResourceType \
  IfcConstructionMaterialResource \
  IfcConstructionMaterialResourceType \
  IfcConstructionProductResource \
  IfcConstructionProductResourceType \
  IfcConstructionResource \
  IfcConstructionResourceType \
  IfcContext \
  IfcCoordinatedUniversalTimeOffset \
  IfcCostItem \
  IfcCostSchedule \
  IfcCostValue\
  IfcCrewResource \
  IfcCrewResourceType \
  IfcDateAndTime \
  IfcEnvironmentalImpactValue \
  IfcEvent \
  IfcEventTime \
  IfcEventType \
  IfcGeographicElement \
  IfcGeographicElementType \
  IfcGrid \
  IfcGridAxis \
  IfcGridPlacement \
  IfcGroup \
  IfcInventory \
  IfcIrregularTimeSeries \
  IfcIrregularTimeSeriesValue \
  IfcLaborResource \
  IfcLaborResourceType \
  IfcLagTime \
  IfcLocalTime \
  IfcMetric \
  IfcMove \
  IfcObject \
  IfcObjectDefinition \
  IfcObjective \
  IfcOccupant \
  IfcOrderAction \
  IfcOrganization \
  IfcOwnerHistory \
  IfcPerformanceHistory \
  IfcPermit \
  IfcPerson \
  IfcPersonAndOrganization \
  IfcPostalAddress \
  IfcProcedure \
  IfcProcedureType \
  IfcProcess \
  IfcProduct \
  IfcProject \
  IfcProjectLibrary \
  IfcProjectOrder \
  IfcProjectOrderRecord \
  IfcProxy \
  IfcRecurrencePattern \
  IfcReferencesValueDocument \
  IfcRegularTimeSeries \
  IfcResource \
  IfcResourceTime \
  IfcScheduleTimeControl \
  IfcSchedulingTime \
  IfcSite \
  IfcSubContractResource \
  IfcSubContractResourceType \
  IfcSystem \
  IfcTable \
  IfcTableColumn \
  IfcTableRow \
  IfcTask \
  IfcTaskTime \
  IfcTaskTimeRecurring \
  IfcTaskType \
  IfcTelecomAddress \
  IfcTimePeriod \
  IfcTimeSeries \
  IfcTimeSeriesSchedule \
  IfcTimeSeriesValue \
  IfcTypeObject \
  IfcTypeProcess \
  IfcTypeProduct \
  IfcTypeResource \
  IfcVirtualGridIntersection \
  IfcWorkCalendar \
  IfcWorkControl \
  IfcWorkPlan \
  IfcWorkSchedule \
  IfcWorkTime]]

# -----------------------------------------------------------------------------------------------------
# structural analysis
set type(PR_ANAL) [lsort [list \
  IfcBoundaryCondition \
  IfcBoundaryEdgeCondition \
  IfcBoundaryFaceCondition \
  IfcBoundaryNodeCondition \
  IfcBoundaryNodeConditionWarping \
  IfcConnectionPointEccentricity \
  IfcFailureConnectionCondition \
  IfcRelAssociatesProfileProperties \
  IfcRelConnectsStructuralActivity \
  IfcRelConnectsStructuralElement \
  IfcRelConnectsStructuralMember \
  IfcRelConnectsWithEccentricity \
  IfcRelServicesBuildings \
  IfcSlippageConnectionCondition \
  IfcStructuralAction \
  IfcStructuralActivity \
  IfcStructuralAnalysisModel \
  IfcStructuralConnection \
  IfcStructuralConnectionCondition \
  IfcStructuralCurveAction \
  IfcStructuralCurveConnection \
  IfcStructuralCurveMember \
  IfcStructuralCurveMemberVarying \
  IfcStructuralCurveReaction \
  IfcStructuralItem \
  IfcStructuralLinearAction \
  IfcStructuralLinearActionVarying \
  IfcStructuralLoad \
  IfcStructuralLoadLinearForce \
  IfcStructuralLoadPlanarForce \
  IfcStructuralLoadCase \
  IfcStructuralLoadConfiguration \
  IfcStructuralLoadGroup \
  IfcStructuralLoadOrResult \
  IfcStructuralLoadSingleDisplacement \
  IfcStructuralLoadSingleDisplacementDistortion \
  IfcStructuralLoadSingleForce \
  IfcStructuralLoadSingleForceWarping \
  IfcStructuralLoadStatic \
  IfcStructuralLoadTemperature \
  IfcStructuralMember \
  IfcStructuralPlanarAction \
  IfcStructuralPlanarActionVarying \
  IfcStructuralPointAction \
  IfcStructuralPointConnection \
  IfcStructuralPointReaction \
  IfcStructuralReaction \
  IfcStructuralResultGroup \
  IfcStructuralSurfaceAction \
  IfcStructuralSurfaceConnection \
  IfcStructuralSurfaceMember \
  IfcStructuralSurfaceMemberVarying \
  IfcStructuralSurfaceReaction \
  IfcSurfaceReinforcementArea]]

# -----------------------------------------------------------------------------------------------------
# electrical
set type(PR_ELEC) [lsort [list \
  IfcAudioVisualAppliance \
  IfcAudioVisualApplianceType \
  IfcCableCarrierFitting \
  IfcCableCarrierFittingType \
  IfcCableCarrierSegment \
  IfcCableCarrierSegmentType \
  IfcCableFitting \
  IfcCableFittingType \
  IfcCableSegment \
  IfcCableSegmentType \
  IfcCommunicationsAppliance \
  IfcCommunicationsApplianceType \
  IfcDistributionCircuit \
  IfcElectricalBaseProperties \
  IfcElectricalCircuit \
  IfcElectricalElement \
  IfcElectricAppliance \
  IfcElectricApplianceType \
  IfcElectricDistributionBoard \
  IfcElectricDistributionBoardType \
  IfcElectricDistributionPoint \
  IfcElectricFlowStorageDevice \
  IfcElectricFlowStorageDeviceType \
  IfcElectricGenerator \
  IfcElectricGeneratorType \
  IfcElectricHeaterType \
  IfcElectricMotor \
  IfcElectricMotorType \
  IfcElectricTimeControl \
  IfcElectricTimeControlType \
  IfcJunctionBox \
  IfcJunctionBoxType \
  IfcLamp \
  IfcLampType \
  IfcLightFixture \
  IfcLightFixtureType \
  IfcMotorConnection \
  IfcMotorConnectionType \
  IfcOutlet \
  IfcOutletType \
  IfcProtectiveDevice \
  IfcProtectiveDeviceTrippingUnit \
  IfcProtectiveDeviceTrippingUnitType \
  IfcProtectiveDeviceType \
  IfcSolarDevice \
  IfcSolarDeviceType \
  IfcSpaceHeaterType \
  IfcSwitchingDevice \
  IfcSwitchingDeviceType \
  IfcTransformer \
  IfcTransformerType]]

# -----------------------------------------------------------------------------------------------------
# hvac, plumbing, building controls
set type(PR_HVAC) [lsort [list \
  IfcActuator \
  IfcActuatorType \
  IfcAirTerminal \
  IfcAirTerminalBox \
  IfcAirTerminalBoxType \
  IfcAirTerminalType \
  IfcAirToAirHeatRecovery \
  IfcAirToAirHeatRecoveryType \
  IfcAlarm \
  IfcAlarmType \
  IfcBoiler \
  IfcBoilerType \
  IfcBurner \
  IfcBurnerType \
  IfcChiller \
  IfcChillerType \
  IfcCoil \
  IfcCoilType \
  IfcCompressor \
  IfcCompressorType \
  IfcCondenser \
  IfcCondenserType \
  IfcControl \
  IfcController \
  IfcControllerType \
  IfcCooledBeam \
  IfcCooledBeamType \
  IfcCoolingTower \
  IfcCoolingTowerType \
  IfcDamper \
  IfcDamperType \
  IfcDistributionElement \
  IfcDistributionElementType \
  IfcDuctFitting \
  IfcDuctFittingType \
  IfcDuctSegment \
  IfcDuctSegmentType \
  IfcDuctSilencer \
  IfcDuctSilencerType \
  IfcEngine \
  IfcEngineType \
  IfcEquipmentStandard \
  IfcEvaporativeCooler \
  IfcEvaporativeCoolerType \
  IfcEvaporator \
  IfcEvaporatorType \
  IfcFan \
  IfcFanType \
  IfcFilter \
  IfcFilterType \
  IfcFireSuppressionTerminal \
  IfcFireSuppressionTerminalType \
  IfcFlowInstrument \
  IfcFlowInstrumentType \
  IfcFlowMeter \
  IfcFlowMeterType \
  IfcGasTerminalType \
  IfcHeatExchanger \
  IfcHeatExchangerType \
  IfcHumidifier \
  IfcHumidifierType \
  IfcInterceptor \
  IfcInterceptorType \
  IfcMedicalDevice \
  IfcMedicalDeviceType \
  IfcPipeFitting \
  IfcPipeFittingType \
  IfcPipeSegment \
  IfcPipeSegmentType \
  IfcPump \
  IfcPumpType \
  IfcSanitaryTerminal \
  IfcSanitaryTerminalType \
  IfcSensor \
  IfcSensorType \
  IfcSpaceHeater \
  IfcSpaceHeaterType \
  IfcStackTerminal \
  IfcStackTerminalType \
  IfcTank \
  IfcTankType \
  IfcTubeBundle \
  IfcTubeBundleType \
  IfcUnitaryControlElement \
  IfcUnitaryControlElementType \
  IfcUnitaryEquipment \
  IfcUnitaryEquipmentType \
  IfcValve \
  IfcValveType \
  IfcVibrationIsolator \
  IfcVibrationIsolatorType \
  IfcWasteTerminal \
  IfcWasteTerminalType]]
			
# -----------------------------------------------------------------------------------------------------
# building services
set type(PR_SRVC) [lsort [list \
  IfcDistributionChamberElement \
  IfcDistributionChamberElementType \
  IfcDistributionControlElement \
  IfcDistributionControlElementType \
  IfcDistributionFlowElement \
  IfcDistributionFlowElementType \
  IfcDistributionPort \
  IfcDistributionSystem \
  IfcEnergyConversionDevice \
  IfcEnergyConversionDeviceType \
  IfcEnergyProperties \
  IfcFlowController \
  IfcFlowControllerType \
  IfcFlowFitting \
  IfcFlowFittingType \
  IfcFlowMovingDevice \
  IfcFlowMovingDeviceType \
  IfcFlowSegment \
  IfcFlowSegmentType \
  IfcFlowStorageDevice \
  IfcFlowStorageDeviceType \
  IfcFlowTerminal \
  IfcFlowTerminalType \
  IfcFlowTreatmentDevice \
  IfcFlowTreatmentDeviceType \
  IfcFluidFlowProperties \
  IfcServiceLife \
  IfcServiceLifeFactor \
  IfcSoundProperties \
  IfcSoundValue \
  IfcSpaceThermalLoadProperties]]

# -----------------------------------------------------------------------------------------------------
# presentation
set type(PR_PRES) [lsort [list \
  IfcAngularDimension \
  IfcAnnotation \
  IfcAnnotationCurveOccurrence \
  IfcAnnotationFillArea \
  IfcAnnotationFillAreaOccurrence \
  IfcAnnotationOccurrence \
  IfcAnnotationSurface \
  IfcAnnotationSurfaceOccurrence \
  IfcAnnotationSymbolOccurrence \
  IfcAnnotationTextOccurrence \
  IfcBlobTexture \
  IfcColourRgb \
  IfcColourRgbList \
  IfcColourSpecification \
  IfcCurveStyle \
  IfcCurveStyleFont \
  IfcCurveStyleFontAndScaling \
  IfcCurveStyleFontPattern \
  IfcDefinedSymbol \
  IfcDiameterDimension \
  IfcDimensionCalloutRelationship \
  IfcDimensionCurve \
  IfcDimensionCurveDirectedCallout \
  IfcDimensionCurveTerminator \
  IfcDimensionPair \
  IfcDraughtingCallout \
  IfcDraughtingCalloutRelationship \
  IfcDraughtingPreDefinedColour \
  IfcDraughtingPreDefinedCurveFont \
  IfcDraughtingPreDefinedTextFont \
  IfcExternallyDefinedHatchStyle \
  IfcExternallyDefinedSurfaceStyle \
  IfcExternallyDefinedSymbol \
  IfcExternallyDefinedTextFont \
  IfcFillAreaStyle \
  IfcFillAreaStyleHatching \
  IfcFillAreaStyleTiles \
  IfcFillAreaStyleTileSymbolWithStyle \
  IfcImageTexture \
  IfcIndexedColourMap \
  IfcIndexedTextureMap \
  IfcIndexedTriangleTextureMap \
  IfcLightDistributionData \
  IfcLightIntensityDistribution \
  IfcLightSource \
  IfcLightSourceAmbient \
  IfcLightSourceDirectional \
  IfcLightSourceGoniometric \
  IfcLightSourcePositional \
  IfcLightSourceSpot \
  IfcLinearDimension \
  IfcOneDirectionRepeatFactor \
  IfcPixelTexture \
  IfcPlanarBox \
  IfcPlanarExtent \
  IfcPreDefinedColour \
  IfcPreDefinedCurveFont \
  IfcPreDefinedDimensionSymbol \
  IfcPreDefinedItem \
  IfcPreDefinedPointMarkerSymbol \
  IfcPreDefinedSymbol \
  IfcPreDefinedTerminatorSymbol \
  IfcPreDefinedTextFont \
  IfcPresentationItem \
  IfcPresentationLayerAssignment \
  IfcPresentationLayerAssignmentWithStyle \
  IfcPresentationLayerWithStyle \
  IfcPresentationStyle \
  IfcPresentationStyleAssignment \
  IfcProjectionCurve \
  IfcRadiusDimension \
  IfcStructuredDimensionCallout \
  IfcStyledItem \
  IfcStyleModel \
  IfcSurfaceStyle \
  IfcSurfaceStyleLighting \
  IfcSurfaceStyleRefraction \
  IfcSurfaceStyleRendering \
  IfcSurfaceStyleShading \
  IfcSurfaceStyleWithTextures \
  IfcSurfaceTexture \
  IfcSymbolStyle \
  IfcTerminatorSymbol \
  IfcTextLiteral \
  IfcTextLiteralWithExtent \
  IfcTextStyle \
  IfcTextStyleFontModel \
  IfcTextStyleForDefinedFont \
  IfcTextStyleTextModel \
  IfcTextStyleWithMirror \
  IfcTextStyleWithSpacing \
  IfcTextStyleWithBoxCharacteristics \
  IfcTextureCoordinate \
  IfcTextureCoordinateGenerator \
  IfcTextureMap \
  IfcTextureVertex \
  IfcTextureVertexList \
  IfcTwoDirectionRepeatFactor \
  IfcVertexBasedTextureMap]]

# determine IFC geometry entities, i.e. all entities not in any other type
set ifcnot $ifcall
foreach item [array names type] {set ifcnot [lindex [intersect3 $ifcnot $type($item)] 0]}

set ifcnot1 {}
foreach ifc $ifcnot {
  if {[string first "Propert" $ifc] != -1 || \
      [string first "Quantit" $ifc] != -1 || \
      [string first "Materia" $ifc] != -1 || \
      [string first "Unit"   $ifc] != -1 || \
      [string first "Relationship" $ifc] != -1 || \
      [string first "IfcRel" $ifc] == 0 || \
      [string first "IfcDoorStyle" $ifc] == 0 || \
      [string first "IfcWindowStyle" $ifc] == 0 || \
      [string first "IfcDimensionalExponents" $ifc] == 0 || \
      $ifc == "IfcElement" || \
      $ifc == "IfcElementType" || \
      $ifc == "IfcRoot" || \
      $ifc == "IfcStructuralLoadOrResult"} {lappend ifcnot1 $ifc}
}
set ifcnot [lindex [intersect3 $ifcnot $ifcnot1] 0]
set type(PR_GEOM) $ifcnot

global dirs locs

set dirs([join "1.0 0.0 0.0"])  "(X)"
set dirs([join "0.0 1.0 0.0"])  "(Y)"
set dirs([join "0.0 0.0 1.0"])  "(Z)"
set dirs([join "-1.0 0.0 0.0"]) "(-X)"
set dirs([join "0.0 -1.0 0.0"]) "(-Y)"
set dirs([join "0.0 0.0 -1.0"]) "(-Z)"

set dirs([join "1.0 0.0"])      "(X)"
set dirs([join "0.0 1.0"])      "(Y)"
set dirs([join "-1.0 0.0"])     "(-X)"
set dirs([join "0.0 -1.0"])     "(-Y)"

set locs([join "0.0 0.0 0.0"])  "(Origin)"
set locs([join "0.0 0.0"])      "(Origin)"
}
